#!/usr/bin/env python3
"""tools/extract/se-rc.py — generate src/se.rc for windres.

Walks vendor/unpacked/se-extracted/ and writes a windres-compatible .rc
file that embeds each SE WAV under the custom resource type "WAVE",
keyed by the engine's original resource ID. The resulting .res.o links
into openrecet.exe alongside its other resources so audio_init's
FindResourceA(NULL, MAKEINTRESOURCE(id), "WAVE") finds them at runtime
— mirroring how the original engine ships its SE blobs.

Filename convention written by tools/extract/se-wavs.py:
    se_<slot:03d>_id<rid:04x>.wav
We parse `rid` (hex) out of each filename and emit one line:
    <rid_decimal> WAVE "<absolute_path>"
per file. Paths are absolute so windres resolves them regardless of
the invoking shell's cwd.

The +4 column of the SE table (channel/voice-group flag) is dormant
in vendor data (engine-quirks #46) — every embedded WAV plays on SE
path A at runtime, so no per-entry routing metadata goes into the .rc.

Usage:
    python3 tools/extract/se-rc.py [output_rc_path]
    (default output: src/se.rc; called this way by src/Makefile)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT        = Path(__file__).resolve().parent.parent.parent
EXTRACT_DIR = ROOT / "vendor" / "unpacked" / "se-extracted"
OUT_DEFAULT = ROOT / "src" / "se.rc"

ENTRY_RE = re.compile(r"^se_(\d{3})_id([0-9a-fA-F]{4})\.wav$")


def main(argv: list[str]) -> int:
    out_path = Path(argv[1]).resolve() if len(argv) > 1 else OUT_DEFAULT
    if not EXTRACT_DIR.is_dir():
        print(f"error: extract dir missing: {EXTRACT_DIR}", file=sys.stderr)
        print("hint: run `python3 tools/extract/se-wavs.py` first",
              file=sys.stderr)
        return 1

    entries: list[tuple[int, int, Path]] = []
    for p in sorted(EXTRACT_DIR.iterdir()):
        m = ENTRY_RE.match(p.name)
        if not m:
            continue
        slot = int(m.group(1))
        rid  = int(m.group(2), 16)
        entries.append((slot, rid, p.resolve()))

    if not entries:
        print(f"error: no se_*.wav files in {EXTRACT_DIR}", file=sys.stderr)
        print("hint: run `python3 tools/extract/se-wavs.py` first",
              file=sys.stderr)
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* auto-generated by tools/extract/se-rc.py; do not edit */\n")
        f.write("/* SE WAV blobs embedded under custom resource type \"WAVE\" */\n")
        f.write("/* (NOT the standard RT_WAVE / RT_RCDATA — engine quirk).  */\n\n")
        for _slot, rid, abs_path in entries:
            posix = str(abs_path).replace("\\", "/")
            f.write(f'{rid} WAVE "{posix}"\n')

    print(f"se-rc: wrote {len(entries)} entries to "
          f"{out_path.relative_to(ROOT) if out_path.is_relative_to(ROOT) else out_path}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
