/*
 * test_main.c — unit-test driver for the OpenRecet decoders.
 *
 *   make -C tests run             # all tests
 *   make -C tests run -- bmp      # filter by name substring (TODO: passthrough)
 *   ./build/run_tests bmp         # ...or invoke directly
 *
 * Test outcomes:
 *   0 pass, 1 fail (printed message), 2 skip (missing vendor data, etc.)
 *
 * Process exit is 0 iff zero failures. Skips do not count as failures.
 *
 * Registration: add one X(name) line per test to TESTS below. The X-macro
 * expands twice — once to emit the extern decl, once to populate the
 * dispatch table — so the test name appears exactly once in this file
 * and the registry can't drift from the declarations.
 */
#include "t.h"

typedef int (*test_fn)(void);

struct test_case {
    const char *name;
    test_fn     fn;
};

/* ─── test list ────────────────────────────────────────────────────────────
 * Each X(n) declares `extern int test_##n(void);` and registers it as
 * {"n", test_##n}. Group blank lines are cosmetic only.
 */
#define TESTS(X) \
    X(bmp_basic_24bit) \
    X(bmp_color_key) \
    X(bmp_color_key_disabled) \
    X(bmp_top_down) \
    X(bmp_32bit) \
    X(bmp_reject_bad_magic) \
    X(bmp_reject_truncated) \
    X(bmp_reject_unsupported_compression) \
    X(bmp_reject_palettized) \
    \
    X(tga_type2_24bit_bottom_up) \
    X(tga_type2_32bit_top_down) \
    X(tga_type10_rle_single_run) \
    X(tga_type10_rle_mixed) \
    X(tga_type10_rle_split_pixel) \
    X(tga_reject_unsupported_type) \
    X(tga_reject_truncated_uncompressed) \
    X(tga_reject_truncated_rle) \
    \
    X(bmp_lzw_round_trip_vendor) \
    \
    X(lnkdatas_hash_empty) \
    X(lnkdatas_hash_test_vector) \
    X(lnkdatas_hash_vendor) \
    \
    X(lnk_lzss_single_literal) \
    X(lnk_lzss_back_reference_short) \
    X(lnk_lzss_back_reference_extended) \
    X(lnk_lzss_self_overlap) \
    X(lnk_lzss_end_of_stream_mid_ctrl) \
    X(lnk_lzss_back_high_bits) \
    X(lnk_lzss_mixed_flags) \
    X(lnk_lzss_vendor_round_trip) \
    \
    X(tables_buysell_empty) \
    X(tables_buysell_comments_only) \
    X(tables_buysell_ok_toggle) \
    X(tables_buysell_sjis_scalars) \
    X(tables_buysell_msg_arrays) \
    X(tables_buysell_no_trailing_newline) \
    X(tables_buysell_embedded_null_terminates) \
    X(tables_buysell_vendor_shape) \
    \
    X(tables_chara_empty) \
    X(tables_chara_defaults_bit_exact) \
    X(tables_chara_basic_record) \
    X(tables_chara_lv100_alone) \
    X(tables_chara_both_blocks_combined) \
    X(tables_chara_comments_skipped) \
    X(tables_chara_out_of_range_index_guarded) \
    X(tables_chara_lv100_field_permutation) \
    X(tables_chara_vendor_shape) \
    \
    X(tables_enemy_init_pre_baked_names) \
    X(tables_enemy_basic_record) \
    X(tables_enemy_longest_prefix_wins) \
    X(tables_enemy_shorter_prefix_when_no_longer_match) \
    X(tables_enemy_comments_and_blanks_skipped) \
    X(tables_enemy_per_line_drop_reset) \
    X(tables_enemy_unknown_name_silently_skipped) \
    X(tables_enemy_placeholder_records_skip_match) \
    X(tables_enemy_no_trailing_newline) \
    X(tables_enemy_vendor_shape) \
    X(tables_enemy_drop_resolves_via_callback) \
    \
    X(tables_config_empty) \
    X(tables_config_all_live_keys) \
    X(tables_config_makefont_is_noop) \
    X(tables_config_font_sjis) \
    X(tables_config_font_overlong_truncates) \
    X(tables_config_commented_lines_ignored) \
    X(tables_config_vendor_shape) \
    \
    X(tables_model_empty) \
    X(tables_model_basic_one_record) \
    X(tables_model_no_index_threads) \
    X(tables_model_comments_skipped) \
    X(tables_model_fname_default_record_zero) \
    X(tables_model_repeated_slot_increments_count) \
    X(tables_model_overlong_fname_truncates) \
    X(tables_model_out_of_range_index_skipped) \
    X(tables_model_vendor_shape) \
    \
    X(tables_oder_empty) \
    X(tables_oder_one_record) \
    X(tables_oder_level_threads_through) \
    X(tables_oder_sjis_attrs_all_16) \
    X(tables_oder_english_attr_falls_through) \
    X(tables_oder_tabs_are_skipped) \
    X(tables_oder_line_cap_truncates) \
    X(tables_oder_no_trailing_newline) \
    X(tables_oder_vendor_shape) \
    \
    X(tables_snews_empty) \
    X(tables_snews_name_table_basic) \
    X(tables_snews_comments_and_blanks_skipped) \
    X(tables_snews_dungeon_and_section) \
    X(tables_snews_multiple_sections_in_dungeon) \
    X(tables_snews_dungeon_transition_corrupts_prev) \
    X(tables_snews_name_empty_value) \
    X(tables_snews_name_overlong_truncates) \
    X(tables_snews_entry_slot_overflow_dropped) \
    X(tables_snews_vendor_shape) \
    \
    X(tables_tuto_empty) \
    X(tables_tuto_blanks_and_comments) \
    X(tables_tuto_chr0_basic) \
    X(tables_tuto_chr1_basic) \
    X(tables_tuto_no_arg_opcodes) \
    X(tables_tuto_goto_7_ints) \
    X(tables_tuto_goto_short_args_zero) \
    X(tables_tuto_bun0_7_ints) \
    X(tables_tuto_nedan_alias_takaku) \
    X(tables_tuto_nebiki_neage) \
    X(tables_tuto_shoki_kingaku_kettei) \
    X(tables_tuto_aitemu) \
    X(tables_tuto_kensen_7_ints) \
    X(tables_tuto_id_minus_one_sentinel) \
    X(tables_tuto_id_below_minus_one_text_only) \
    X(tables_tuto_file_index_stride) \
    X(tables_tuto_overflows_cap) \
    X(tables_tuto_vendor_like_shape) \
    \
    X(tables_item_empty) \
    X(tables_item_comments_and_blanks_skipped) \
    X(tables_item_basic_record_no_plural) \
    X(tables_item_basic_record_with_plural) \
    X(tables_item_full_stat_fields) \
    X(tables_item_category_header_then_record) \
    X(tables_item_category_threads_to_correct_index) \
    X(tables_item_attr_mask_with_category) \
    X(tables_item_audience_all_via_zen) \
    X(tables_item_audience_male_composite) \
    X(tables_item_audience_recette_only) \
    X(tables_item_audience_empty_field_is_all) \
    X(tables_item_stock_zaiko_basic) \
    X(tables_item_stock_da_x10_quirk) \
    X(tables_item_indent_space_line_skipped) \
    X(tables_item_unknown_line_skipped) \
    X(tables_item_out_of_range_id_dropped) \
    X(tables_item_no_trailing_newline) \
    X(tables_item_description_in_line1_and_line2) \
    X(tables_item_description_slash_terminates_line2) \
    X(tables_item_resolver_finds_singular) \
    X(tables_item_max_records_cap) \
    X(tables_item_vendor_shape) \
    \
    X(tables_gousei_empty) \
    X(tables_gousei_comments_and_blanks_skipped) \
    X(tables_gousei_basic_recipe) \
    X(tables_gousei_rank_header) \
    X(tables_gousei_recipe_before_rank_is_rank_zero) \
    X(tables_gousei_prefix_discarded) \
    X(tables_gousei_three_ingredients) \
    X(tables_gousei_five_ingredients) \
    X(tables_gousei_null_resolver_yields_minus_one) \
    X(tables_gousei_unknown_name_resolves_to_empty) \
    X(tables_gousei_count_at_eol_no_trailing_colon) \
    X(tables_gousei_no_trailing_newline) \
    X(tables_gousei_max_records_cap) \
    X(tables_gousei_embedded_nul_early_exit) \
    X(tables_gousei_vendor_shape) \
    X(tables_gousei_resolves_via_item_state) \
    \
    X(tables_kyaku_empty) \
    X(tables_kyaku_comments_and_blanks_skipped) \
    X(tables_kyaku_header_singular_only) \
    X(tables_kyaku_header_with_plural) \
    X(tables_kyaku_attr_x_y) \
    X(tables_kyaku_attr_empty_value_keeps_defaults) \
    X(tables_kyaku_budget_range) \
    X(tables_kyaku_budget_empty_no_write) \
    X(tables_kyaku_like_kind_resolver_hit) \
    X(tables_kyaku_like_kind_null_resolver_skips) \
    X(tables_kyaku_like_kind_cap_at_20) \
    X(tables_kyaku_like_attr_mask_sjis_tokens) \
    X(tables_kyaku_dislikes_orphan_match_is_noop) \
    X(tables_kyaku_file_path) \
    X(tables_kyaku_activity_time_mask_four_tokens) \
    X(tables_kyaku_activity_time_partial_tokens) \
    X(tables_kyaku_activity_time_unknown_token_ignored) \
    X(tables_kyaku_atoi_scalars) \
    X(tables_kyaku_lines_before_header_dropped) \
    X(tables_kyaku_no_trailing_newline) \
    X(tables_kyaku_multi_customer_threading) \
    X(tables_kyaku_resolves_via_item_category) \
    X(tables_kyaku_vendor_shape) \
    \
    X(tables_event_empty_seeds_default) \
    X(tables_event_layout_byte_offsets) \
    X(tables_event_comments_and_blanks_skipped) \
    X(tables_event_basic_hiroba_record) \
    X(tables_event_prereq_hex_and_minus) \
    X(tables_event_time_first_and_max) \
    X(tables_event_time_max_clamps_to_first_no_higher) \
    X(tables_event_time_unknown_tokens_only) \
    X(tables_event_loop_min_atoi) \
    X(tables_event_day_pairs_up_to_20) \
    X(tables_event_category_dispatch) \
    X(tables_event_data_line_before_header_goes_to_hiroba) \
    X(tables_event_decay_or_max_zero_for_parsed) \
    X(tables_event_no_trailing_newline) \
    X(tables_event_vendor_shape) \
    \
    X(tables_news_empty) \
    X(tables_news_layout_byte_offsets) \
    X(tables_news_comments_and_blanks_skipped) \
    X(tables_news_special_attr_basic) \
    X(tables_news_sjis_attr_mask) \
    X(tables_news_category_resolver_hit) \
    X(tables_news_item_resolver_hit) \
    X(tables_news_lookup_chain_precedence) \
    X(tables_news_days_range_optional) \
    X(tables_news_dash_row) \
    X(tables_news_target_group_sticky) \
    X(tables_news_period_sticky) \
    X(tables_news_period_defaults_apply_before_header) \
    X(tables_news_period_missing_dash_leaves_end_unchanged) \
    X(tables_news_no_trailing_newline) \
    X(tables_news_body_keeps_trailing_cr_on_crlf) \
    X(tables_news_body_strips_on_lf_only) \
    X(tables_news_no_resolver_misses_silently) \
    X(tables_news_max_records_cap) \
    X(tables_news_vendor_shape) \
    \
    X(tables_enemylist_layout_byte_offsets) \
    X(tables_enemylist_empty) \
    X(tables_enemylist_comments_and_blanks_skipped) \
    X(tables_enemylist_wisp_basic) \
    X(tables_enemylist_wisp_empty_value) \
    X(tables_enemylist_wisp10_silent_drop) \
    X(tables_enemylist_wisp_unknown_resolves_minus_one) \
    X(tables_enemylist_dungeon_header_resets_section) \
    X(tables_enemylist_f_no_dash_single_floor) \
    X(tables_enemylist_f_empty_skips) \
    X(tables_enemylist_multiple_f_lines_thread) \
    X(tables_enemylist_enemy_basic_one_drop) \
    X(tables_enemylist_enemy_multi_drops) \
    X(tables_enemylist_variant_suffix) \
    X(tables_enemylist_count_suffix) \
    X(tables_enemylist_longest_prefix_wins) \
    X(tables_enemylist_unknown_enemy_skipped) \
    X(tables_enemylist_drop_reset_per_line) \
    X(tables_enemylist_no_resolver_drops_minus_one) \
    X(tables_enemylist_no_trailing_newline) \
    X(tables_enemylist_enemies_thread_across_f_blocks) \
    X(tables_enemylist_vendor_shape) \
    \
    X(tables_stage_layout_byte_offsets) \
    X(tables_stage_empty) \
    X(tables_stage_lines_before_first_header_dropped) \
    X(tables_stage_comments_and_blanks_skipped) \
    X(tables_stage_defaults_applied_on_open) \
    X(tables_stage_id_dispatch_short_keys) \
    X(tables_stage_id_dispatch_long_keys) \
    X(tables_stage_id_unknown_falls_back_to_1_16) \
    X(tables_stage_int_fields) \
    X(tables_stage_float_fields) \
    X(tables_stage_flag_fields) \
    X(tables_stage_string_fields) \
    X(tables_stage_map_slots_thread) \
    X(tables_stage_map_overflow_safe) \
    X(tables_stage_mapcamera_slots_thread) \
    X(tables_stage_fog_pair) \
    X(tables_stage_fog_one_value_keeps_default_second) \
    X(tables_stage_int_triples) \
    X(tables_stage_float_triples_colon) \
    X(tables_stage_maplight_d_a_space_pairs) \
    X(tables_stage_sunpos_numeric_sets_mode_1) \
    X(tables_stage_sunpos_off_sets_mode_0) \
    X(tables_stage_sunset_numeric_sets_mode_2) \
    X(tables_stage_sunset_off_broken_quirk_36) \
    X(tables_stage_moonpos_quirk_35_shares_coords_keeps_sun_mode) \
    X(tables_stage_multiple_records_thread) \
    X(tables_stage_no_trailing_newline) \
    X(tables_stage_vendor_shape_minified) \
    \
    X(recet_ini_empty_applies_defaults) \
    X(recet_ini_default_pad_skill_tables) \
    X(recet_ini_screen_lookup_all_branches) \
    X(recet_ini_screen_drives_width_height) \
    X(recet_ini_all_setup_scalars) \
    X(recet_ini_option_pad_grid) \
    X(recet_ini_section_and_key_case_insensitive) \
    X(recet_ini_comments_and_blanks_skipped) \
    X(recet_ini_whitespace_around_equals) \
    X(recet_ini_bgnodisp_mirrors_easydisp) \
    X(recet_ini_volume_clamp) \
    X(recet_ini_unknown_keys_and_sections_ignored) \
    X(recet_ini_no_trailing_newline) \
    X(recet_ini_vendor_shape) \
    \
    X(rng_initial_seed_is_one) \
    X(rng_msvc_rand_sequence_from_seed_1) \
    X(rng_seed_resets_state) \
    X(rng_next_unit_range_zero_to_just_under_one) \
    X(rng_next_unit_seed_1_first_values) \
    X(rng_compute_seed_year_2000_jan_1) \
    X(rng_compute_seed_year_range_rejects) \
    X(rng_compute_seed_leap_bump_post_february) \
    X(rng_compute_seed_is_deterministic) \
    \
    X(math_vec3_normalize_3_4_0) \
    X(math_vec3_normalize_in_place) \
    X(math_lookat_z_back_camera) \
    X(math_lookat_off_axis) \
    X(math_perspective_fov_pi_over_2_aspect_1) \
    X(math_perspective_aspect_changes_w_only) \
    X(math_mul_identity_identity_is_identity) \
    X(math_mul_handles_output_alias) \
    X(math_mul_diagonal_scaling) \
    \
    X(prewindow_named_globals_set) \
    X(prewindow_object_table_y_set_first_last) \
    X(prewindow_object_table_other_fields_zero) \
    X(prewindow_particles_alive_flag_all_one) \
    X(prewindow_particles_pos_within_expected_range) \
    X(prewindow_particle_zero_deterministic_from_seed_1) \
    X(prewindow_advances_rng_by_600) \
    X(prewindow_proj_matrix_is_finite) \
    X(prewindow_view_is_degenerate_nan_or_inf) \
    \
    X(tick_init_zeros_state) \
    X(tick_speed_thresholds_match_rdata) \
    X(tick_first_frame_huge_delta_ticks_once) \
    X(tick_speed_one_runs_sim_twice) \
    X(tick_speed_four_runs_sim_five_times) \
    X(tick_delayed_far_from_frame_returns_5ms_sleep) \
    X(tick_delayed_close_to_frame_busy_spins) \
    X(tick_delayed_input_polls_after_frame_boundary) \
    X(tick_state_one_skips_sim_render) \
    X(tick_state_two_transitions_to_one) \
    X(tick_no_device_aborts_after_sim_before_render) \
    X(tick_state_alt_copies_state_seed) \
    X(tick_per_frame_flags_clear_on_ticked) \
    X(tick_per_frame_flags_not_cleared_on_delayed) \
    X(tick_null_callbacks_are_safe) \
    X(tick_adaptive_sleep_scales_with_remaining) \
    X(tick_steady_state_60fps_carries_residue) \
    X(tick_pending_speed_latches_at_top_of_frame) \
    \
    X(input_joy_decode_centered_pov_no_axes_no_buttons) \
    X(input_joy_decode_pov_eight_directions) \
    X(input_joy_decode_stick_axes_set_dpad) \
    X(input_joy_decode_pov_axes_or_together) \
    X(input_joy_decode_buttons_only_high_bit_matters) \
    X(input_apply_joystick_block_default_pad_one) \
    X(input_apply_joystick_block_virtual_base_offsets_per_joy) \
    X(input_apply_joystick_block_skill_slots_set_byte_plus_one) \
    X(input_apply_joystick_block_zero_binding_never_matches) \
    X(input_apply_joystick_block_ors_into_existing_mask) \
    X(input_apply_keyboard_block_default_pad_zero) \
    X(input_apply_keyboard_block_z_key_for_button_a) \
    X(input_apply_keyboard_block_low_bit_set_does_not_count) \
    X(input_apply_keyboard_block_out_of_range_binding_skipped) \
    X(input_apply_keyboard_block_skill_slots) \
    X(input_bindings_load_default_ini_matches_engine_layout) \
    X(input_bindings_load_round_trips_modified_ini) \
    X(input_dik_table_matches_vendor_dump) \
    X(input_binding_mask_dpad_face_buttons_layout) \
    X(input_state_stride_matches_engine) \
    \
    X(input_trace_parse_single_line) \
    X(input_trace_parse_sparse_three_lines) \
    X(input_trace_parse_decimal_buttons) \
    X(input_trace_parse_skips_comments_and_blank_lines) \
    X(input_trace_parse_buttons_key_first_also_works) \
    X(input_trace_parse_rejects_out_of_order_frames) \
    X(input_trace_parse_rejects_duplicate_frames) \
    X(input_trace_parse_rejects_unknown_key) \
    X(input_trace_parse_rejects_missing_buttons) \
    X(input_trace_parse_rejects_mask_above_16_bit) \
    X(input_trace_parse_empty_buffer) \
    X(input_trace_lookup_before_first_returns_zero) \
    X(input_trace_lookup_holds_between_entries) \
    X(input_trace_lookup_empty_trace) \
    X(input_trace_load_round_trips_real_file) \
    X(input_trace_load_missing_file_returns_zero) \
    X(input_trace_record_emits_first_frame_and_changes) \
    X(input_trace_record_reopen_truncates) \
    X(input_trace_record_when_closed_is_noop) \
    X(input_trace_record_open_rejects_null) \
    \
    X(render_quad_init_seeds_z_rhw_specular) \
    X(render_quad_add_one_emits_six_vertices) \
    X(render_quad_uv_half_texel_inset_asymmetry) \
    X(render_quad_scale_widens_and_offsets) \
    X(render_quad_offset_shifts_top_left) \
    X(render_quad_top_left_truncated_to_int) \
    X(render_quad_returns_zero_when_full) \
    X(render_quad_rejects_zero_tex_dim) \
    X(render_quad_reset_keeps_z_rhw_prefill) \
    X(render_quad_init_zero_screen_w_defaults_640) \
    X(render_quad_rotated_zero_rotation_axis_aligned) \
    X(render_quad_rotated_quarter_turn_rolls_corners) \
    X(render_quad_rotated_scales_by_screen_w) \
    X(render_quad_rotated_does_not_touch_vertex_counter) \
    X(render_quad_rotated_preserves_z_rhw_specular) \
    \
    X(scene_title_assets_count_is_seven) \
    X(scene_title_assets_paths_match_pe) \
    X(scene_title_assets_sizes_power_of_two) \
    X(scene_title_assets_sizes_match_engine) \
    X(scene_title_menu_fresh_boot_4_items) \
    X(scene_title_menu_has_save_no_adv8_6_items) \
    X(scene_title_menu_has_save_and_score_7_items) \
    X(scene_title_menu_full_unlock_8_items) \
    X(scene_title_menu_hidden_char_only_5_items) \
    X(scene_title_menu_survival_requires_both_flags) \
    \
    X(scene_title_anim_init_fresh_seeds_folding_out) \
    X(scene_title_sim_frame_counter_advances_on_idle) \
    X(scene_title_sim_pulse_phase_ticks_every_frame) \
    X(scene_title_sim_cursor_anim_clamps_at_zero) \
    X(scene_title_sim_down_held_wraps_cursor) \
    X(scene_title_sim_up_held_wraps_cursor_backwards) \
    X(scene_title_sim_a_pressed_starts_select_phase) \
    X(scene_title_sim_select_phase_pins_at_fifteen) \
    X(scene_title_sim_pending_action_default_is_none) \
    X(scene_title_sim_fade_counter_set_on_new_game) \
    X(scene_title_sim_pending_action_exit_on_exit_item) \
    X(scene_title_sim_fade_counter_advances_after_set) \
    X(scene_title_sim_cursor_input_ignored_while_select_pending) \
    X(scene_title_sim_cursor_pressed_only_no_held) \
    X(scene_title_sim_frame_counter_clamps_at_pre_movie_window) \
    X(scene_title_sim_null_guards) \
    \
    X(settings_a_on_options_transitions_to_state_2) \
    X(settings_input_gated_during_slide_in) \
    X(settings_down_wraps_cursor_mod_six) \
    X(settings_up_wraps_cursor_backwards) \
    X(settings_left_decrements_bgm) \
    X(settings_left_clamps_bgm_floor) \
    X(settings_right_clamps_bgm_ceiling) \
    X(settings_each_row_targets_correct_state) \
    X(settings_clear_row_consumes_a_press_no_exit) \
    X(settings_a_exits_clean_with_dirty_3) \
    X(settings_a_exits_dirty_with_dirty_2) \
    X(settings_b_also_exits) \
    X(settings_dirty_flag_cleared_on_re_entry) \
    X(settings_options_dispatch_does_not_set_pending_action) \
    X(settings_main_menu_other_actions_still_publish) \
    X(settings_reset_seeds_engine_defaults) \
    X(settings_slider3_clamps_to_range) \
    X(settings_slider4_clamps_to_range) \
    X(settings_round_trip_each_legal_value) \
    \
    X(save_bank_arena_sizing) \
    X(save_bank_bank_pointer_arithmetic) \
    X(save_bank_init_all_seeds_header_magic) \
    X(save_bank_init_all_seeds_slider_defaults) \
    X(save_bank_init_all_stamps_all_banks) \
    X(save_bank_init_all_is_idempotent) \
    X(save_bank_init_one_sets_money_and_objective) \
    X(save_bank_init_one_fills_item_slot_spans) \
    X(save_bank_init_one_mini_block) \
    X(save_bank_init_one_chara_records) \
    X(save_bank_init_one_consumes_8_rng_steps) \
    X(save_bank_checksum_detects_tamper) \
    X(save_bank_header_init_hook_fires_once_per_reset) \
    X(save_bank_header_slider_setters_clamp) \
    \
    X(sysassets_compute_icon_sizes_empty_state) \
    X(sysassets_compute_icon_sizes_single_item_minimum_64) \
    X(sysassets_compute_icon_sizes_eight_items_still_64) \
    X(sysassets_compute_icon_sizes_nine_items_grows_to_96) \
    X(sysassets_compute_icon_sizes_seventeen_items_yields_96) \
    X(sysassets_compute_icon_sizes_invalid_records_skipped) \
    X(sysassets_compute_icon_sizes_multi_category) \
    X(sysassets_compute_icon_sizes_out_of_range_category_skipped) \
    X(sysassets_compute_icon_sizes_max_category_tracker_skips_revisits) \
    X(sysassets_compute_icon_sizes_large_category_count) \
    X(sysassets_chara_variant_count_matches_engine_stride) \
    X(sysassets_item_category_slot_count_matches_table) \
    \
    X(sim_button_ring_first_press_sets_pressed) \
    X(sim_button_ring_held_clears_pressed_next_frame) \
    X(sim_button_ring_repeat_pulses_after_settle) \
    X(sim_button_ring_release_drops_held) \
    X(sim_button_ring_multiple_bits_independent) \
    X(sim_init_zeros_state) \
    X(sim_step_a_advances_frame_count) \
    X(sim_step_a_pipes_input_into_ring) \
    X(sim_loading_pump_pure_cold_start_is_noop) \
    X(sim_loading_pump_pure_990_cycles_to_1f_then_wraps) \
    X(sim_loading_pump_pure_994_wraps_at_threshold) \
    X(sim_loading_pump_pure_994_threshold_zero_wraps_immediately) \
    X(sim_loading_pump_pure_998_mode0_cycles_to_13_then_wraps) \
    X(sim_loading_pump_pure_998_mode1_clamps_at_0xc) \
    X(sim_loading_pump_module_globals) \
    X(sim_init_zeros_counter_state) \
    X(sim_step_a_busy_freezes_input_and_dispatch) \
    X(sim_step_a_idle_clears_nowloading_gate) \
    \
    X(music_init_engine_data_defaults) \
    X(music_select_title_bare_returns_track_zero) \
    X(music_select_title_bare_holds_until_fade_band) \
    X(music_select_title_fade_band_returns_none) \
    X(music_select_title_stop_sentinel) \
    X(music_select_title_post_stop_no_change) \
    X(music_select_title_submenu_open_uses_table_lookup) \
    X(music_select_title_invalid_language_falls_back_to_zero) \
    X(music_select_forced_override_wins) \
    X(music_select_pause_modal_routes_to_over) \
    X(music_select_pause_modal_other_b_not_one_skips_override) \
    X(music_select_state_7_returns_none) \
    X(music_select_state_9_no_quest_returns_none) \
    X(music_select_state_9_quest_pending_returns_fanfare) \
    X(music_select_town_states_return_track_one) \
    X(music_step_increments_frame_count) \
    X(music_step_title_bare_dispatches_track_zero_once) \
    X(music_step_speed_drops_to_0_75_at_state_10) \
    X(music_step_global_pause_blocks_dispatch) \
    X(music_step_se_stop_pending_sweeps_and_clears) \
    X(music_step_pending_fade_phase_latches) \
    X(music_step_no_modal_clears_fade_and_forced) \
    X(music_step_paused_b_keeps_forced_track) \
    X(music_step_target_volume_default_is_one) \
    X(music_step_target_volume_fade_band_decreases) \
    X(music_step_stop_sentinel_dispatches_track_minus_two) \
    X(music_step_forced_override_dispatches_overridden_track) \
    X(music_step_fade_phase_advances_progress) \
    X(music_step_fade_phase_one_walks_to_silence) \
    X(music_step_fade_phase_two_walks_to_loud) \
    X(music_step_no_fade_skips_apply_hook) \
    X(music_step_pending_fade_phase_drives_animation) \
    \
    X(audio_bgm_table_has_21_entries) \
    X(audio_bgm_table_well_known_indices) \
    X(audio_bgm_filename_bounds) \
    X(audio_one_shot_set_is_exact) \
    X(audio_music_bridge_fires_on_swap) \
    X(audio_music_bridge_skipped_when_null) \
    \
    X(audio_mci_buffer_size_is_4800_bytes) \
    X(audio_mci_clear_zeroes_buffer) \
    X(audio_mci_basic_copy_at_row_zero_col_zero) \
    X(audio_mci_nul_early_exit_writes_nothing) \
    X(audio_mci_row_and_column_indexing) \
    X(audio_mci_stops_at_first_nul_in_source) \
    X(audio_mci_full_80_byte_fill_no_terminator) \
    X(audio_mci_source_longer_than_cap_truncates) \
    X(audio_mci_repeated_record_at_same_slot_overwrites) \
    X(audio_mci_channel_offset_spans_into_next_row) \
    \
    X(audio_fade_frame_zero_is_hard_silence) \
    X(audio_fade_frame_nine_is_target) \
    X(audio_fade_frames_one_to_eight_monotonic_increasing) \
    X(audio_fade_intermediate_value_matches_reference) \
    X(audio_fade_target_threading_at_frame_five) \
    X(audio_fade_out_of_range_clamps) \
    X(audio_fade_slider_defaults_to_nine) \
    X(audio_fade_slider_set_clamps_to_0_9) \
    X(audio_fade_channel_centibel_matches_compute) \
    X(audio_fade_apply_calls_hook_with_centibel) \
    X(audio_fade_apply_skips_hook_when_unset) \
    X(audio_fade_apply_rejects_invalid_channel) \
    X(audio_fade_progress_phase1_starts_loud) \
    X(audio_fade_progress_phase1_ends_silent) \
    X(audio_fade_progress_phase1_monotonic_decreasing) \
    X(audio_fade_progress_phase2_starts_silent) \
    X(audio_fade_progress_phase2_ends_loud) \
    X(audio_fade_progress_phase2_monotonic_increasing) \
    X(audio_fade_progress_lower_slider_attenuates_peak) \
    X(audio_fade_progress_slider_clamped) \
    X(audio_fade_progress_progress_clamped_and_overshoot) \
    X(audio_fade_progress_degenerate_duration_falls_back_to_slider) \
    X(audio_fade_apply_progress_drives_hook) \
    X(audio_fade_apply_progress_rejects_invalid_channel) \
    \
    X(audio_trace_json_escape_passthrough_ascii) \
    X(audio_trace_json_escape_quote) \
    X(audio_trace_json_escape_backslash) \
    X(audio_trace_json_escape_newlines_and_tabs) \
    X(audio_trace_json_escape_non_ascii_to_u_form) \
    X(audio_trace_json_escape_truncates_safely) \
    X(audio_trace_json_escape_null_safe) \
    X(audio_trace_open_close_idempotent) \
    X(audio_trace_open_rejects_null) \
    X(audio_trace_emit_bgm_swap_writes_one_line) \
    X(audio_trace_emit_fade_start_writes_one_line) \
    X(audio_trace_emit_when_closed_is_noop) \
    \
    X(audio_se_table_has_110_entries) \
    X(audio_se_table_first_and_last_ids) \
    X(audio_se_table_out_of_order_swap_at_39_40) \
    X(audio_se_table_jumps_to_high_range_at_slot_69) \
    X(audio_se_table_skips_2c3) \
    X(audio_se_resource_id_bounds) \
    X(audio_se_table_resource_type_is_custom) \
    X(audio_play_se_rejects_out_of_range) \
    X(audio_play_se_emits_trace_event) \
    X(audio_play_se_no_trace_when_closed) \
    X(audio_se_table_matches_vendor_bytes) \
    \
    X(fade_reset_zeroes_state) \
    X(fade_phase1_start_seeds_state) \
    X(fade_phase_out_start_seeds_state) \
    X(fade_tick_idle_is_noop) \
    X(fade_tick_phase1_clamps_at_duration_plus_one) \
    X(fade_tick_phase_out_resets_at_end) \
    X(fade_is_done_idle_returns_zero) \
    X(fade_is_done_phase1_matches_duration) \
    X(fade_is_done_phase_out_never_returns_one) \
    X(fade_is_done_mode2_uses_0x1f_pin) \
    \
    X(scene_set_title_writes_title_and_zero_substate) \
    X(scene_post_fade_init_lands_in_ingame) \
    X(scene_post_fade_init_clears_substate) \
    X(scene_post_fade_init_starts_fade_in) \
    \
    X(nowloading_reset_zeroes_state) \
    X(nowloading_set_active_normalises_to_zero_one) \
    X(nowloading_tick_idle_decays_alpha_by_32) \
    X(nowloading_tick_active_advances_rotation_by_0_3) \
    X(nowloading_tick_active_does_not_decay_alpha) \
    X(nowloading_tick_idle_does_not_advance_rotation) \
    X(nowloading_tick_returns_previous_gate_state) \
    \
    X(worker_load_case_count_is_seventeen) \
    X(worker_load_reset_zeroes_all_state) \
    X(worker_load_begin_raises_busy_and_nowloading) \
    X(worker_load_end_clears_busy_only) \
    X(worker_load_set_cb_round_trip) \
    X(worker_load_set_cb_out_of_range_silently_ignored) \
    X(worker_load_set_cb_overwrites_existing) \
    X(worker_load_dispatch_invokes_registered_cb) \
    X(worker_load_dispatch_unregistered_slot_is_noop) \
    X(worker_load_dispatch_out_of_range_returns_zero) \
    X(worker_load_dispatch_each_slot_independent) \
    X(worker_load_dispatch_does_not_touch_busy) \
    X(worker_load_close_is_idempotent_without_handle) \
    X(worker_load_spawn_non_win32_only_raises_gates) \
    X(worker_load_secondary_busy_defaults_zero) \
    X(worker_load_alt_cb_round_trip) \
    X(worker_load_alt_dispatch_invokes_registered_cb) \
    X(worker_load_alt_dispatch_with_no_cb_returns_one) \
    X(worker_load_alt_dispatch_does_not_touch_busy) \
    X(worker_load_alt_spawn_non_win32_only_raises_gates) \
    X(worker_load_alt_full_cycle_simulation) \
    X(worker_load_reset_clears_alt_cb) \
    X(worker_load_engine_dispatch_full_cycle_simulation) \
    X(worker_load_sec_body_count_is_nine) \
    X(worker_load_sec_body_set_get_round_trip) \
    X(worker_load_sec_body_out_of_range_silently_ignored) \
    X(worker_load_sec_d07_pre_spawn_round_trip) \
    X(worker_load_begin_secondary_raises_busy_and_nowloading) \
    X(worker_load_end_secondary_clears_busy_only) \
    X(worker_load_dispatch_sec_invokes_registered_cb) \
    X(worker_load_dispatch_sec_out_of_range_returns_zero) \
    X(worker_load_dispatch_sec_unregistered_slot_is_noop) \
    X(worker_load_sec_post_body_aab_writes_three_flags) \
    X(worker_load_sec_post_body_ae8_writes_1cc_no_fade) \
    X(worker_load_sec_post_body_b13_writes_1cc_no_fade) \
    X(worker_load_sec_post_body_b3e_writes_1d4_and_fade_kicks_on_param_eq_one) \
    X(worker_load_sec_post_body_b3e_no_fade_when_param_ne_one) \
    X(worker_load_sec_post_body_b82_bc6_c0a_share_1d4_fade_pattern) \
    X(worker_load_sec_post_body_c4e_writes_1d0_with_fade) \
    X(worker_load_sec_post_body_c96_writes_1d8_with_fade) \
    X(worker_load_sec_post_body_out_of_range_is_noop) \
    X(worker_load_spawn_d07_raises_gates_latches_param_runs_pre_spawn) \
    X(worker_load_spawn_d3e_pending_cc_eq_two) \
    X(worker_load_spawn_d85_dc1_dfd_e39_share_pending_1d4) \
    X(worker_load_spawn_e75_pending_1d0) \
    X(worker_load_spawn_eb1_pending_1d8) \
    X(worker_load_reset_zeroes_secondary_state) \
    X(worker_load_sec_full_cycle_simulation_b3e) \
    X(worker_load_sec_full_cycle_simulation_c4e) \
    X(worker_load_sec_full_cycle_simulation_aab_no_fade) \
    \
    X(save_io_scan_fresh_arena_zero_flags) \
    X(save_io_scan_score_in_bank_set) \
    X(save_io_scan_adv_cleared_requires_score_and_flag) \
    X(save_io_scan_adv8_in_items_list) \
    X(save_io_scan_adv8_range_full_coverage) \
    X(save_io_scan_hidden_char_from_header) \
    X(save_io_scan_bank99_also_scanned) \
    X(save_io_scan_caps_bogus_item_count) \
    X(save_io_try_load_returns_zero_when_no_files) \
    X(save_io_try_load_returns_one_when_primary_exists) \
    X(save_io_try_load_falls_back_to_backup) \
    X(save_io_try_load_oversized_file_reinits) \
    X(save_io_try_load_arena_sized_file_copies_verbatim) \
    X(save_io_known_format_flag_modern) \
    X(save_io_known_format_flag_stays_zero_on_fallback) \
    X(save_io_write_arena_writes_both_files) \
    X(save_io_write_arena_null_paths_skipped) \
    X(save_io_write_arena_one_null_succeeds) \
    X(save_io_write_then_load_round_trip) \
    \
    X(font_init_zeros_state) \
    X(font_init_is_idempotent) \
    X(font_age_tick_advances_in_use_only) \
    X(font_age_tick_all_free_is_noop) \
    X(font_age_tick_does_not_touch_other_fields) \
    \
    X(font_atlas_record_size_is_40) \
    X(font_atlas_record_field_offsets) \
    X(font_atlas_special_table_size_is_576) \
    X(font_atlas_special_table_first_entry_is_fullwidth_space) \
    X(font_atlas_special_table_known_punctuation) \
    X(font_atlas_special_table_no_internal_nul) \
    X(font_atlas_padded_dim_zero_mod_4) \
    X(font_atlas_padded_dim_one_mod_4) \
    X(font_atlas_padded_dim_two_mod_4) \
    X(font_atlas_padded_dim_three_mod_4) \
    X(font_atlas_blit_zeroes_yield_zeroes) \
    X(font_atlas_blit_alpha_to_high_nibble_marker_in_low) \
    X(font_atlas_blit_clamps_alpha_at_15) \
    X(font_atlas_blit_keeps_alpha_zero_pixels_at_zero) \
    X(font_atlas_blit_skips_when_dst_too_small) \
    X(font_atlas_dilate_no_glyph_no_change) \
    X(font_atlas_dilate_glyph_body_unchanged) \
    X(font_atlas_dilate_neighbor_gets_intensity_15_within_edgewi) \
    X(font_atlas_dilate_neighbor_falloff_outside_edgewi) \
    X(font_atlas_dilate_skip_low_alpha_propagation) \
    X(font_atlas_dilate_does_not_overwrite_glyph_body) \
    X(font_atlas_dilate_neighbor_keeps_brighter_existing_halo) \
    X(font_atlas_pack_record_basic) \
    X(font_atlas_pack_record_zero_box_zero_pad) \
    X(font_atlas_load_missing_returns_zero) \
    X(font_atlas_load_basic_roundtrip) \
    X(font_atlas_load_rejects_bad_idx_size) \
    X(font_atlas_free_is_idempotent) \
    \
    X(font_codepoint_ascii_is_byte_value) \
    X(font_codepoint_high_byte_below_table_returns_none_if_missing) \
    X(font_codepoint_special_table_first_entry) \
    X(font_codepoint_special_table_known_punctuation) \
    X(font_codepoint_sjis_double_byte_at_boundary) \
    X(font_codepoint_sjis_double_byte_high_kanji) \
    X(font_slot_alloc_first_call_gets_slot_zero) \
    X(font_slot_alloc_match_returns_existing_resets_age) \
    X(font_slot_alloc_distinct_codepoints_get_distinct_slots) \
    X(font_slot_alloc_unknown_codepoint_returns_none) \
    X(font_slot_alloc_double_byte_codepoint_stores_both_bytes) \
    X(font_slot_alloc_match_double_byte_requires_both) \
    X(font_slot_alloc_eviction_via_age_gate) \
    X(font_slot_alloc_release_callback_fires_on_evict) \
    X(font_slot_alloc_no_callback_still_nulls_texture) \
    \
    X(font_upload_expand_transparent_byte) \
    X(font_upload_expand_body_pixel_white_full) \
    X(font_upload_expand_body_pixel_dim) \
    X(font_upload_expand_edge_only_pixel) \
    X(font_upload_expand_alpha_nibble_only) \
    X(font_upload_expand_edge_nibble_only) \
    \
    X(scene_walls_count_is_fifteen) \
    X(scene_walls_filename_table_first_and_last) \
    X(scene_walls_filename_table_full_order) \
    X(scene_walls_filename_out_of_range_is_null) \
    X(scene_walls_format_string) \
    X(scene_walls_load_param0_loads_only_selector) \
    X(scene_walls_load_param1_loads_everything_except_selector) \
    X(scene_walls_load_default_selector_zero) \
    X(scene_walls_load_selector_out_of_range_param0_loads_nothing) \
    X(scene_walls_load_selector_out_of_range_param1_loads_all) \
    X(scene_walls_load_without_load_fn_returns_count_only) \
    X(scene_walls_reset_zeroes_state) \
    \
    X(scene_floor_count_is_fifteen) \
    X(scene_floor_filename_table_first_and_last) \
    X(scene_floor_filename_table_full_order) \
    X(scene_floor_filename_out_of_range_is_null) \
    X(scene_floor_format_string) \
    X(scene_floor_load_param0_loads_only_selector) \
    X(scene_floor_load_param1_loads_everything_except_selector) \
    X(scene_floor_load_default_selector_zero) \
    X(scene_floor_load_selector_out_of_range_param0_loads_nothing) \
    X(scene_floor_load_selector_out_of_range_param1_loads_all) \
    X(scene_floor_load_without_load_fn_returns_count_only) \
    X(scene_floor_reset_zeroes_state) \
    X(scene_floor_load_all_paths_prefixed) \
    X(scene_floor_selector_independent_from_walls) \
    \
    X(scene_jutan_count_is_eight) \
    X(scene_jutan_filename_table_first_and_last) \
    X(scene_jutan_filename_table_full_order) \
    X(scene_jutan_filename_out_of_range_is_null) \
    X(scene_jutan_format_string) \
    X(scene_jutan_load_param0_loads_only_selector) \
    X(scene_jutan_load_param1_loads_everything_except_selector) \
    X(scene_jutan_load_default_selector_zero) \
    X(scene_jutan_load_selector_out_of_range_param0_loads_nothing) \
    X(scene_jutan_load_selector_out_of_range_param1_loads_all) \
    X(scene_jutan_load_without_load_fn_returns_count_only) \
    X(scene_jutan_reset_zeroes_state) \
    X(scene_jutan_load_all_paths_prefixed) \
    X(scene_jutan_selector_independent_from_siblings) \
    \
    X(scene_pause_load_count_is_twenty) \
    X(scene_pause_slot0_default_is_pause_tga) \
    X(scene_pause_slot0_selector_2_is_endless) \
    X(scene_pause_slot0_selector_3_is_endless) \
    X(scene_pause_slot0_selector_other_values_are_pause) \
    X(scene_pause_filename_table_full_order) \
    X(scene_pause_filename_out_of_range_is_null) \
    X(scene_pause_slot_dims_pause_and_singletons) \
    X(scene_pause_slot_dims_sousa_all_400x200) \
    X(scene_pause_slot_dims_status_all_200x200) \
    X(scene_pause_slot_dims_out_of_range_returns_zero) \
    X(scene_pause_load_dispatches_all_twenty) \
    X(scene_pause_load_paths_match_filename_table) \
    X(scene_pause_load_dims_match_metadata) \
    X(scene_pause_load_selector_endless_swaps_slot_zero) \
    X(scene_pause_load_without_load_fn_returns_count_only) \
    X(scene_pause_state_init_writes_constants) \
    X(scene_pause_state_init_is_idempotent) \
    X(scene_pause_state_init_overrides_dirty_state) \
    X(scene_pause_reset_zeroes_state) \
    X(scene_pause_selector_independent_from_siblings) \
    \
    X(scene_buy_slot_count_is_ten) \
    X(scene_buy_page_count_is_fifty) \
    X(scene_buy_format_string) \
    X(scene_buy_singleton_slots_are_distinct) \
    X(scene_buy_ae8_zero_count_loads_only_singletons) \
    X(scene_buy_ae8_zero_valid_loads_only_singletons) \
    X(scene_buy_ae8_default_state_loads_only_singletons) \
    X(scene_buy_ae8_dynamic_loop_three_items) \
    X(scene_buy_ae8_dynamic_loop_full_ten_items) \
    X(scene_buy_ae8_dynamic_loop_count_overflow_is_clamped) \
    X(scene_buy_ae8_null_load_fn_returns_count_only) \
    X(scene_buy_ae8_singleton_paths_match_rdata) \
    X(scene_buy_ae8_ignores_current_page_selector) \
    X(scene_buy_b13_default_page_zero_loads_nothing) \
    X(scene_buy_b13_page0_with_items) \
    X(scene_buy_b13_indexes_by_current_page) \
    X(scene_buy_b13_zero_valid_at_current_page_is_noop) \
    X(scene_buy_b13_out_of_range_page_is_noop) \
    X(scene_buy_b13_count_overflow_is_clamped) \
    X(scene_buy_b13_null_load_fn_returns_count_only) \
    X(scene_buy_b13_does_not_load_singletons) \
    X(scene_buy_reset_zeroes_state) \
    \
    X(scene_worldmap_count_is_four) \
    X(scene_worldmap_filename_table_full_order) \
    X(scene_worldmap_filename_out_of_range_is_null) \
    X(scene_worldmap_dims_match_engine_calls) \
    X(scene_worldmap_dims_out_of_range_zeroes_outputs) \
    X(scene_worldmap_load_dispatches_all_four) \
    X(scene_worldmap_load_paths_match_filename_table) \
    X(scene_worldmap_load_dims_match_metadata) \
    X(scene_worldmap_load_without_load_fn_returns_count) \
    X(scene_worldmap_body_slot_starts_null) \
    X(scene_worldmap_mappoint_is_tall_unique) \
    \
    X(xfile_bad_header) \
    X(xfile_empty) \
    X(xfile_bare_mesh) \
    X(xfile_full_mesh) \
    X(xfile_frame_hierarchy) \
    X(xfile_hyphen_stitch) \
    X(xfile_vendor_ice01) \
    X(xfile_vendor_corpus) \
    X(xfile_vendor_xfile2_corpus) \
    \
    X(mesh_empty) \
    X(mesh_single_triangle) \
    X(mesh_vertex_colors_diffuse) \
    X(mesh_vertex_colors_partial) \
    X(mesh_vertex_colors_absent) \
    X(mesh_bounds_cube) \
    X(mesh_vendor_ice01) \
    X(mesh_vendor_corpus) \
    \
    X(mesh_load_classify_water) \
    X(mesh_load_classify_kabe) \
    X(mesh_load_classify_yuka_n) \
    X(mesh_load_classify_shop_jutan) \
    X(mesh_load_classify_hikari) \
    X(mesh_load_classify_w_prefix) \
    X(mesh_load_classify_u_index) \
    X(mesh_load_classify_v_index) \
    X(mesh_load_classify_empty) \
    X(mesh_load_cache_dedupe) \
    X(mesh_load_cache_capacity) \
    X(mesh_load_from_buf_synthetic) \
    X(mesh_load_from_buf_no_texture) \
    X(mesh_load_vendor_corpus) \
    \
    X(mesh_draw_resolve_slot_basic) \
    X(mesh_draw_resolve_slot_no_texture) \
    X(mesh_draw_resolve_slot_oob_material) \
    X(mesh_draw_resolve_slot_null_inputs) \
    X(mesh_draw_resolve_slot_stale_past_cache) \
    \
    X(stage_state_house_defaults) \
    X(stage_state_idempotent) \
    X(stage_state_overwrites_stale) \
    \
    X(stage_palette_size) \
    X(stage_palette_offsets) \
    X(stage_palette_init_house_pointer) \
    X(stage_palette_init_house_zeroes) \
    X(stage_palette_init_house_zeroes_padding) \
    X(stage_palette_init_house_idempotent) \
    \
    X(scene_table_introspection) \
    X(scene_table_param1_loads_non_selector) \
    X(scene_table_param0_loads_only_selector) \
    X(scene_table_oob_selector_param0) \
    X(scene_table_oob_selector_param1) \
    X(scene_table_pair_slot_order) \
    X(scene_table_null_loader_dry_run) \
    \
    X(scene_sc1_dormant_default) \
    X(scene_sc1_var_mesh_loop) \
    X(scene_sc1_var_sprite_loop) \
    X(scene_sc1_item_loop_skips_empty) \
    X(scene_sc1_cap_clamps_count) \
    X(scene_sc1_null_callbacks_count_only) \
    \
    X(scene1_spawn_first_call_recorded) \
    X(scene1_spawn_ring_wraps) \
    X(scene1_spawn_reset_clears) \
    X(scene1_spawn_type_60_commits_slot_zero) \
    X(scene1_spawn_busy_slots_skipped) \
    X(scene1_spawn_full_table_no_crash) \
    X(scene1_spawn_unimplemented_type_no_commit) \
    X(scene1_spawn_type_20_age_zero) \
    X(scene1_spawn_type_66_velocity_down) \
    X(scene1_spawn_type_66_param1_distribution) \
    X(scene1_spawn_type_1_commits_8) \
    X(scene1_spawn_type_2_commits_8) \
    X(scene1_spawn_type_3_commits_8) \
    X(scene1_spawn_type_52_commits_8) \
    X(scene1_spawn_type_5e_commits_8) \
    X(scene1_spawn_type_65_commits_8) \
    X(scene1_spawn_type_92_commits_1) \
    X(scene1_spawn_type_79_commits_128) \
    X(scene1_spawn_type_5d_commits_45) \
    X(scene1_spawn_type_52_vy_positive_bias) \
    X(scene1_spawn_type_1_vy_can_be_negative) \
    X(scene1_spawn_type_92_vy_negative) \
    X(scene1_spawn_type_92_param_ranges) \
    X(scene1_spawn_type_79_age_stagger) \
    X(scene1_spawn_type_5d_age_and_param1_negate_index) \
    X(scene1_spawn_type_5d_pos_uses_4x_velocity) \
    X(scene1_spawn_type_1_pos_uses_3x_velocity) \
    X(scene1_spawn_type_65_halves_magnitude) \
    X(scene1_spawn_type_69_commits_128) \
    X(scene1_spawn_type_68_commits_1) \
    X(scene1_spawn_type_73_commits_2) \
    X(scene1_spawn_type_77_commits_2) \
    X(scene1_spawn_type_99_commits_1) \
    X(scene1_spawn_type_78_commits_1) \
    X(scene1_spawn_type_69_age_stagger) \
    X(scene1_spawn_type_69_pos_uses_3x_velocity) \
    X(scene1_spawn_type_68_anchor_back_48x) \
    X(scene1_spawn_type_73_param7_drives_angle) \
    X(scene1_spawn_type_77_same_body_as_73) \
    X(scene1_spawn_type_99_anchor_back_40x_and_base) \
    X(scene1_spawn_type_78_sets_param2_param7) \
    X(scene1_spawn_type_78_matches_99_when_param7_zero) \
    X(scene1_spawn_type_53_commits_1) \
    X(scene1_spawn_type_4a_commits_8) \
    X(scene1_spawn_type_43_commits_24) \
    X(scene1_spawn_type_97_commits_64) \
    X(scene1_spawn_type_96_commits_64) \
    X(scene1_spawn_type_40_commits_8) \
    X(scene1_spawn_type_4e_commits_3) \
    X(scene1_spawn_type_36_param7_drives_count) \
    X(scene1_spawn_type_74_param7_drives_count) \
    X(scene1_spawn_type_36_param7_zero_clamps_to_one) \
    X(scene1_spawn_type_53_positive_vy) \
    X(scene1_spawn_type_4a_param1_eq_param7) \
    X(scene1_spawn_type_4a_age_stagger) \
    X(scene1_spawn_type_4a_pos_exact) \
    X(scene1_spawn_type_43_pos_y_anchored_below) \
    X(scene1_spawn_type_43_rot_y_matches_angle) \
    X(scene1_spawn_type_97_scale_halved) \
    X(scene1_spawn_type_96_camera_drives_xz_bend) \
    X(scene1_spawn_type_96_scale_full_range) \
    X(scene1_spawn_type_40_ring_angle_steps) \
    X(scene1_spawn_type_40_vy_positive) \
    X(scene1_spawn_type_36_rescales_slot_scale) \
    X(scene1_spawn_type_4e_vel_xz_narrowed_vs_pos) \
    X(scene1_spawn_type_34_commits_24) \
    X(scene1_spawn_type_35_commits_1) \
    X(scene1_spawn_type_2c_commits_32) \
    X(scene1_spawn_type_29_commits_14) \
    X(scene1_spawn_type_32_commits_2) \
    X(scene1_spawn_type_4c_commits_1) \
    X(scene1_spawn_type_55_commits_1) \
    X(scene1_spawn_type_4b_commits_3) \
    X(scene1_spawn_type_57_commits_1) \
    X(scene1_spawn_type_3e_commits_4) \
    X(scene1_spawn_type_33_param7_drives_count) \
    X(scene1_spawn_type_4d_param7_drives_count) \
    X(scene1_spawn_type_51_param7_drives_count) \
    X(scene1_spawn_type_34_age_stagger) \
    X(scene1_spawn_type_34_vel_x_equals_mag_times_scale) \
    X(scene1_spawn_type_34_pos_uses_anchor_back_24x) \
    X(scene1_spawn_type_35_pos_exact) \
    X(scene1_spawn_type_2c_age_stagger) \
    X(scene1_spawn_type_2c_pos_uses_20x_velocity) \
    X(scene1_spawn_type_29_pos_stays_at_param) \
    X(scene1_spawn_type_29_vel_no_scale) \
    X(scene1_spawn_type_32_rot_angle_steps) \
    X(scene1_spawn_type_4c_vel_x_sign_alternates) \
    X(scene1_spawn_type_4b_vel_x_count_driven) \
    X(scene1_spawn_type_4b_scale_decays_per_particle) \
    X(scene1_spawn_type_57_param2_eq_param7) \
    X(scene1_spawn_type_57_rot_z_sign_on_param7) \
    X(scene1_spawn_type_3e_rot_x_steps) \
    X(scene1_spawn_type_3d_commits_20) \
    X(scene1_spawn_type_6c_commits_1) \
    X(scene1_spawn_type_6e_commits_1) \
    X(scene1_spawn_type_1f_commits_1) \
    X(scene1_spawn_type_100_commits_1) \
    X(scene1_spawn_type_23_commits_1) \
    X(scene1_spawn_type_22_commits_20) \
    X(scene1_spawn_type_3c_commits_20) \
    X(scene1_spawn_type_5a_commits_20) \
    X(scene1_spawn_type_2d_commits_20) \
    X(scene1_spawn_type_1d_commits_1) \
    X(scene1_spawn_type_6d_param7_drives_count) \
    X(scene1_spawn_type_45_param7_drives_count) \
    X(scene1_spawn_type_3d_age_stagger) \
    X(scene1_spawn_type_3d_param1_eq_param7) \
    X(scene1_spawn_type_3d_base_eq_param) \
    X(scene1_spawn_type_6d_camera_yaw_drives_pos) \
    X(scene1_spawn_type_6d_param2_in_range) \
    X(scene1_spawn_type_45_no_param2_tag) \
    X(scene1_spawn_type_6c_vel_zero) \
    X(scene1_spawn_type_6e_vel_targets_base) \
    X(scene1_spawn_type_1f_scene_counter_drives_pos) \
    X(scene1_spawn_type_100_same_body_as_1f) \
    X(scene1_spawn_type_23_preamble_only) \
    X(scene1_spawn_type_22_age_stagger) \
    X(scene1_spawn_type_3c_base_y_lifted) \
    X(scene1_spawn_type_5a_age_stagger) \
    X(scene1_spawn_type_2d_age_stagger) \
    X(scene1_spawn_type_2d_pos_relative_to_param) \
    X(scene1_spawn_type_1d_vel_scale_12) \
    X(scene1_spawn_type_1d_param2_eq_param7) \
    X(scene1_spawn_mega_group_type_25_commits_12) \
    X(scene1_spawn_mega_group_type_37_commits_12) \
    X(scene1_spawn_mega_group_type_46_commits_12) \
    X(scene1_spawn_mega_group_type_7a_commits_12) \
    X(scene1_spawn_mega_group_type_84_commits_12) \
    X(scene1_spawn_mega_group_type_86_commits_12) \
    X(scene1_spawn_mega_group_type_90_commits_12) \
    X(scene1_spawn_mega_group_type_85_not_member) \
    X(scene1_spawn_mega_group_type_29_not_member) \
    X(scene1_spawn_mega_group_param2_color_in_range) \
    X(scene1_spawn_mega_group_rot_y_sign_alternates) \
    X(scene1_spawn_mega_group_rot_x_raw_unit) \
    X(scene1_spawn_mega_group_pos_offsets_param) \
    X(scene1_spawn_mega_group_all_types_share_rng_sequence) \
    X(scene1_spawn_type_19_commits_1) \
    X(scene1_spawn_type_44_commits_1) \
    X(scene1_spawn_type_94_commits_1) \
    X(scene1_spawn_type_2e_commits_1) \
    X(scene1_spawn_type_1e_commits_1) \
    X(scene1_spawn_type_1a_commits_1) \
    X(scene1_spawn_type_5f_commits_1) \
    X(scene1_spawn_type_4_commits_1) \
    X(scene1_spawn_type_70_commits_1) \
    X(scene1_spawn_type_1c_commits_1) \
    X(scene1_spawn_type_42_commits_1) \
    X(scene1_spawn_type_2a_commits_1) \
    X(scene1_spawn_type_13_commits_1) \
    X(scene1_spawn_type_14_commits_1) \
    X(scene1_spawn_type_24_commits_1) \
    X(scene1_spawn_type_6_commits_1) \
    X(scene1_spawn_type_7_commits_1) \
    X(scene1_spawn_type_8_commits_1) \
    X(scene1_spawn_type_9_commits_1) \
    X(scene1_spawn_type_11_commits_1) \
    X(scene1_spawn_type_12_commits_1) \
    X(scene1_spawn_type_54_commits_1) \
    X(scene1_spawn_type_50_commits_1) \
    X(scene1_spawn_type_19_preamble_only) \
    X(scene1_spawn_type_1a_param2_eq_param7) \
    X(scene1_spawn_type_5f_rot_z_in_range) \
    X(scene1_spawn_rot_z_group_shares_body) \
    X(scene1_spawn_type_42_rot_y_and_z) \
    X(scene1_spawn_type_2a_param1_eq_param7) \
    X(scene1_spawn_type_13_param1_eq_param7) \
    X(scene1_spawn_type_14_param1_eq_param7) \
    X(scene1_spawn_type_24_param1_and_arm) \
    X(scene1_spawn_type_6_param2_snapshots_global) \
    X(scene1_spawn_types_6_to_9_share_body) \
    X(scene1_spawn_type_11_const_vel) \
    X(scene1_spawn_type_12_param1_eq_param7) \
    X(scene1_spawn_type_54_param1_eq_param7) \
    X(scene1_spawn_type_50_copies_block) \
    X(scene1_spawn_type_50_block_default_zero) \
    X(scene1_spawn_type_5_param7_drives_count) \
    X(scene1_spawn_type_5c_param7_drives_count) \
    X(scene1_spawn_type_6f_param7_drives_count) \
    X(scene1_spawn_type_10_param7_drives_count) \
    X(scene1_spawn_type_b_param7_drives_count) \
    X(scene1_spawn_type_c_param7_drives_count) \
    X(scene1_spawn_type_e_param7_drives_count) \
    X(scene1_spawn_type_2b_param7_drives_count) \
    X(scene1_spawn_type_1b_param7_drives_count) \
    X(scene1_spawn_type_3b_param7_drives_count) \
    X(scene1_spawn_type_76_param7_drives_count) \
    X(scene1_spawn_type_67_param7_drives_count) \
    X(scene1_spawn_type_59_param7_drives_count) \
    X(scene1_spawn_type_71_param7_drives_count) \
    X(scene1_spawn_type_0f_commits_8) \
    X(scene1_spawn_type_5_param7_zero_clamps_to_one) \
    X(scene1_spawn_unit_half_group_shares_body) \
    X(scene1_spawn_type_5_vy_centered) \
    X(scene1_spawn_type_67_vy_positive_bias) \
    X(scene1_spawn_type_59_pos_anchor_back) \
    X(scene1_spawn_type_59_vy_positive) \
    X(scene1_spawn_type_71_life_cap_and_age) \
    X(scene1_spawn_type_71_vy_positive) \
    X(scene1_spawn_type_0f_age_stagger) \
    X(scene1_spawn_type_0f_consumes_dead_rng15) \
    /* C8i.5c — 9 multi-stage handlers (camera-yaw trig + aux_15 flag) */ \
    X(scene1_spawn_type_15_param7_drives_count) \
    X(scene1_spawn_type_16_param7_drives_count) \
    X(scene1_spawn_type_18_param7_drives_count) \
    X(scene1_spawn_type_58_param7_drives_count) \
    X(scene1_spawn_type_4f_param7_drives_count) \
    X(scene1_spawn_type_3f_param7_drives_count) \
    X(scene1_spawn_type_56_param7_drives_count) \
    X(scene1_spawn_type_h10_param7_drives_count) \
    X(scene1_spawn_type_91_param7_drives_count) \
    X(scene1_spawn_type_15_velocity_uses_scale) \
    X(scene1_spawn_type_16_vel_y_zero) \
    X(scene1_spawn_type_16_world_radial_xz) \
    X(scene1_spawn_type_18_vel_x_positive_bias) \
    X(scene1_spawn_type_18_camera_yaw_drives_pos) \
    X(scene1_spawn_type_58_param2_400_or_200) \
    X(scene1_spawn_type_58_vy_bounded) \
    X(scene1_spawn_type_58_no_age_write) \
    X(scene1_spawn_type_4f_velx_equals_mag_velz_zero) \
    X(scene1_spawn_type_4f_vy_negative) \
    X(scene1_spawn_type_3f_56_share_body) \
    X(scene1_spawn_type_3f_vel_xz_zero_vy_positive) \
    X(scene1_spawn_type_h10_aux_15_zero_when_param7_lt_10) \
    X(scene1_spawn_type_h10_aux_15_one_when_param7_ge_10) \
    X(scene1_spawn_type_91_aux_15_one_when_param7_ge_10) \
    X(scene1_spawn_type_h10_vy_halved_when_param7_lt_10) \
    X(scene1_spawn_type_h10_param1_signed_range) \
    X(scene1_mesh_emit_records_call) \
    X(scene1_mesh_emit_reset_clears) \
    \
    X(particles_tick_empty_tables_noop) \
    X(particles_tick_ignores_unported_types) \
    X(particles_tick_type_6_initial_position) \
    X(particles_tick_type_7_8_9_share_body) \
    X(particles_tick_type_6_kills_on_scene_dead) \
    X(particles_tick_type_6_interp_saturates) \
    X(particles_tick_type_20_snaps_to_origin) \
    X(particles_tick_type_20_spawns_every_4_ticks) \
    X(particles_tick_type_20_kills_on_scene_dead) \
    X(particles_tick_type_21_basic_velocity_and_rotation) \
    X(particles_tick_type_21_kills_at_age_0x20) \
    X(particles_tick_type_21_no_snap_when_param2_minus1) \
    X(particles_tick_type_21_kills_when_table_b_empty) \
    X(particles_tick_type_21_lives_when_table_b_active) \
    X(particles_tick_chain_20_to_21_records_spawn) \
    \
    X(particles_tick_type_43_decay_drift) \
    X(particles_tick_type_43_kills_at_0x18) \
    X(particles_tick_type_68_no_damp) \
    X(particles_tick_type_29_gravity) \
    X(particles_tick_type_96_rot_bumps) \
    X(particles_tick_type_60_age_cap) \
    X(particles_tick_type_60_kill_at_0x960) \
    X(particles_tick_type_5d_param1_kill) \
    X(particles_tick_type_36_kill_at_param1) \
    X(particles_tick_type_4b_field_decay) \
    X(particles_tick_type_32_constant_rot) \
    X(particles_tick_type_71_double_step) \
    X(particles_tick_type_59_expanding) \
    X(particles_tick_type_25_huge_group) \
    X(particles_tick_type_50_pure_age) \
    X(particles_tick_type_10_param1_gravity) \
    X(particles_tick_type_4_rot_drip) \
    \
    X(particles_tick_type_92_rot_spin) \
    X(particles_tick_type_92_kills_at_0x100) \
    X(particles_tick_type_18_sin_drives_vy) \
    X(particles_tick_type_34_lives_and_orbits) \
    X(particles_tick_type_34_chains_35_on_death) \
    X(particles_tick_type_35_pos_snaps_to_player) \
    X(particles_tick_type_35_kills_at_0x30) \
    \
    X(particles_tick_type_99_baseline_drift_anchor) \
    X(particles_tick_type_99_kills_at_0x18) \
    X(particles_tick_type_23_hard_snap) \
    X(particles_tick_type_23_kills_at_0x30) \
    X(particles_tick_type_22_drift_and_damp) \
    X(particles_tick_type_22_kills_at_0x20) \
    X(particles_tick_type_3c_gravity_and_kill) \
    X(particles_tick_type_5a_yonly_baseline_drift) \
    X(particles_tick_type_5a_kills_at_0x30) \
    X(particles_tick_type_98_drift_and_damp) \
    X(particles_tick_type_98_kill_on_close_distance) \
    X(particles_tick_type_98_kills_at_0x40) \
    X(particles_tick_type_2c_first_tick_no_move) \
    X(particles_tick_type_2c_reverse_drift) \
    X(particles_tick_type_41_snap_to_ground) \
    X(particles_tick_type_41_kills_at_100) \
    X(particles_tick_type_62_lives_when_counter_high) \
    X(particles_tick_type_62_dies_when_counter_low) \
    X(particles_tick_type_61_no_snap_kill_at_300) \
    X(particles_tick_type_3d_orbit_basic) \
    X(particles_tick_type_3d_kill_from_param1) \
    X(particles_tick_type_6e_drifts_then_emits_mesh) \
    X(particles_tick_type_6e_no_drift_past_101) \
    X(particles_tick_type_6e_kills_at_0x74) \
    X(particles_tick_type_6d_baseline_y_as_gravity) \
    X(particles_tick_type_6d_kills_at_param2) \
    X(particles_tick_type_6c_early_stage_buoyancy) \
    X(particles_tick_type_6c_kills_at_600) \
    X(particles_tick_type_1d_anchors_to_table_b) \
    X(particles_tick_type_1d_kills_at_0xd) \
    X(particles_tick_type_1d_oob_param2_safe) \
    X(particles_tick_type_2d_buoyant_drift) \
    \
    X(particles_tick_type_1a_anchors_when_alive) \
    X(particles_tick_type_1a_chains_type_1_when_dead) \
    X(particles_tick_type_1a_oob_param2_safe) \
    X(particles_tick_type_78_anchors_to_target) \
    X(particles_tick_type_78_kills_at_0x18) \
    X(particles_tick_type_75_drift_and_damp) \
    X(particles_tick_type_93_close_distance_kill) \
    X(particles_tick_type_75_kills_at_0x40) \
    X(particles_tick_type_12_gate_closed_lives) \
    X(particles_tick_type_12_gate_open_drifts_and_age) \
    X(particles_tick_type_14_no_drift_just_counter) \
    X(particles_tick_type_12_kills_at_param2_0x3c) \
    X(particles_tick_type_12_oob_param1_safe) \
    \
    X(particles_tick_type_4a_zero_rotation) \
    X(particles_tick_type_4a_rot_y_quarter_turn) \
    X(particles_tick_type_4a_advances_rotations) \
    X(particles_tick_type_4a_npc_anchor) \
    X(particles_tick_type_4a_oob_param1_safe) \
    X(particles_tick_type_4a_kills_at_0x18) \
    X(particles_tick_type_34_rotation_is_applied) \
    \
    X(scene1_ingame_tick_runs_integrator) \
    X(sim_step_a_state_ingame_runs_integrator) \
    X(sim_step_a_state_title_skips_integrator) \
    X(sim_step_a_state_ingame_100_ticks) \
    X(sim_step_a_state_2_runs_integrator) \
    X(sim_step_a_state_3_runs_integrator) \
    X(sim_step_a_state_b_runs_integrator) \
    X(sim_step_a_state_10_runs_integrator) \
    X(sim_step_a_state_4_skips_integrator) \
    X(sim_step_a_state_5_skips_integrator) \
    X(sim_step_a_state_a_skips_integrator) \
    X(sim_step_a_state_c_skips_integrator) \
    X(scene1_ingame_default_arm_ticks_particles_and_c) \
    X(scene1_ingame_transition_flag_picks_transition_arm) \
    X(scene1_ingame_skip_flag_skips_all_ticks) \
    X(scene1_ingame_paused_flag_picks_transition_arm) \
    X(scene1_ingame_transition_arm_tick_direct) \
    X(scene1_ingame_default_arm_tick_direct) \
    X(scene1_ingame_transition_flag_takes_precedence_over_skip) \
    X(sim_step_a_state_ingame_default_arm_also_ticks_c) \
    \
    X(scene1_postload_stage_defaults_match_fun_0044f13d) \
    X(scene1_postload_init_stage_defaults_is_idempotent) \
    X(scene1_postload_pose_player_copies_defaults) \
    X(scene1_postload_ambient_spawn_no_palette_is_noop) \
    X(scene1_postload_ambient_spawn_flag_zero_is_noop) \
    X(scene1_postload_force_ambient_flag_writes_palette) \
    X(scene1_postload_force_ambient_flag_null_safe) \
    X(scene1_postload_ambient_spawn_runs_200_iterations) \
    X(scene1_postload_ambient_spawn_records_type_4f) \
    X(scene1_postload_ambient_spawn_param2_is_100) \
    X(scene1_postload_ambient_spawn_uses_player_pos_y_plus_2) \
    X(scene1_postload_set_force_ambient_bypasses_palette_gate) \
    X(scene1_postload_set_force_ambient_zero_restores_gate) \
    X(scene1_postload_set_force_ambient_null_palette_still_noop) \
    X(scene1_postload_type_override_replaces_4f) \
    X(scene1_postload_type_override_minus_one_restores_default) \
    X(scene1_postload_ambient_spawn_tick_advances_records) \
    X(scene1_postload_smoke_c_default_is_noop) \
    X(scene1_postload_smoke_c_pickup_writes_first_slot) \
    X(scene1_postload_smoke_c_world_drop_commits_count) \
    X(scene1_postload_smoke_c_pickup_plus_world_drop_both_fire) \
    X(scene1_postload_smoke_c_uses_player_pos_y_plus_2_when_no_override) \
    X(scene1_postload_smoke_c_setter_minus_one_restores_default) \
    X(scene1_postload_smoke_c_world_drop_count_zero_is_skip) \
    X(scene1_postload_smoke_b_default_is_noop) \
    X(scene1_postload_smoke_b_npc_writes_first_slot) \
    X(scene1_postload_smoke_b_entity_writes_first_slot) \
    X(scene1_postload_smoke_b_npc_plus_entity_both_fire) \
    X(scene1_postload_smoke_b_uses_player_pos_y_plus_2_when_no_override) \
    X(scene1_postload_smoke_b_setter_minus_one_restores_default) \
    X(scene1_postload_smoke_b_blob_persists_matrix_across_calls) \
    \
    X(scene1_camera_init_clears_orient) \
    X(scene1_camera_house_default_snaps_to_oracle_pose) \
    X(scene1_camera_anchor_alias_tracks_lookat) \
    X(scene1_camera_char_mode_below_2_collapses_offsets) \
    X(scene1_camera_yaw_orbits_eye) \
    X(scene1_camera_floor_bias_converges_to_fixed_point) \
    X(scene1_camera_yaw_change_lerps_eye) \
    X(scene1_camera_angle_writes_orient_matrix) \
    X(scene1_camera_angle_singular_dist_skips_write) \
    X(scene1_camera_view_matches_lookat_rh_when_z_roll_zero) \
    X(scene1_camera_view_applies_z_roll_when_nonzero) \
    X(scene1_postload_pose_override_replaces_player_pos) \
    X(scene1_postload_pose_override_disable_restores_player_pos) \
    \
    X(scene1_pass_d_should_emit_rejects_sentinel) \
    X(scene1_pass_d_should_emit_accepts_match_types) \
    X(scene1_pass_d_should_emit_rejects_adjacent_types) \
    X(scene1_pass_d_compose_translation_only) \
    X(scene1_pass_d_compose_scale_factor_is_point_2) \
    X(scene1_pass_d_compose_rotation_x_mixes_y_z) \
    X(scene1_pass_d_compose_scale_field_is_float_not_int) \
    X(scene1_pass_d_mesh_default_is_null) \
    X(scene1_pass_d_mesh_setter_round_trips) \
    X(scene1_pass_d_mesh_setter_replaces_previous) \
    X(scene1_debug_pass_d_unlit_default_is_off) \
    X(scene1_debug_pass_d_unlit_setter_round_trips) \
    X(scene1_debug_pass_d_unlit_normalises_to_0_or_1) \
    X(scene1_preload_post_house_cb_default_is_null) \
    X(scene1_preload_post_house_cb_setter_round_trips) \
    X(scene1_preload_post_house_cb_setter_replaces_previous) \
    \
    X(wf_pass_c_should_emit_rejects_sentinel) \
    X(wf_pass_c_should_emit_accepts_cardinal_0_1_2_3) \
    X(wf_pass_c_should_emit_rejects_out_of_range) \
    X(wf_pass_c_scale_default_is_point_0192) \
    X(wf_pass_c_scale_aux_1_is_smaller) \
    X(wf_pass_c_scale_aux_2_is_larger) \
    X(wf_pass_c_scale_aux_3_falls_through_to_default) \
    X(wf_pass_c_tile_index_type_0_age_0) \
    X(wf_pass_c_tile_index_type_1_age_3_is_9) \
    X(wf_pass_c_tile_index_type_2_age_21_wraps_to_16) \
    X(wf_pass_c_tile_index_type_3_age_20_max_in_row) \
    X(wf_pass_c_uv_box_tile_0_top_left_corner) \
    X(wf_pass_c_uv_box_tile_8_wraps_to_row_1) \
    X(wf_pass_c_uv_box_tile_30_row_3_col_6) \
    X(wf_pass_c_pre_matrix_default_is_identity) \
    X(wf_pass_c_pre_matrix_setter_round_trips) \
    X(wf_pass_c_pre_matrix_setter_ignores_null) \
    X(wf_pass_c_compose_world_default_pre_matrix_is_scale_translate) \
    X(wf_pass_c_compose_world_smaller_aux_1_scale) \
    X(wf_pass_a_should_emit_rejects_sentinel) \
    X(wf_pass_a_should_emit_accepts_0x77) \
    X(wf_pass_a_should_emit_accepts_0xa2) \
    X(wf_pass_a_should_emit_rejects_neighboring_types) \
    X(wf_pass_a_scale_full_at_age_5) \
    X(wf_pass_a_scale_zero_at_age_0) \
    X(wf_pass_a_scale_ramps_in_over_5_frames) \
    X(wf_pass_a_scale_uses_life_mult) \
    X(wf_pass_a_compose_world_translation_in_row_3) \
    X(wf_pass_a_compose_world_rot_x_pi_cancels_rot_z) \
    \
    X(records_c_tick_empty_table_is_noop) \
    X(records_c_tick_sentinel_slots_skipped) \
    X(records_c_tick_aux_flag_net_zero_age) \
    X(records_c_tick_pickup_bob_sparkle_at_age_10) \
    X(records_c_tick_pickup_bob_lifts_in_range) \
    X(records_c_tick_pickup_bob_no_lift_outside_range) \
    X(records_c_tick_pickup_commit_kills_at_age_0x78) \
    X(records_c_tick_world_drop_drag_and_gravity) \
    X(records_c_tick_world_drop_attract_to_player) \
    X(records_c_tick_world_drop_speed_cap) \
    X(records_c_tick_world_drop_ground_bounce) \
    X(records_c_tick_world_drop_kill_at_age_0xf0) \
    X(records_c_tick_world_drop_kill_at_pos_y_below_minus_1) \
    X(records_c_tick_overflow_eviction_is_dormant) \
    X(records_c_tick_non_world_drop_type_no_kill_check) \
    X(records_c_tick_ground_clamp_non_world_drop_advances_state) \
    X(records_c_offset_type_is_10) \
    X(records_c_reset_sentinels_at_offset_10) \
    \
    X(records_c_spawn_pickup_writes_first_free_slot) \
    X(records_c_spawn_pickup_skips_alive_slots) \
    X(records_c_spawn_pickup_table_full_is_noop) \
    X(records_c_spawn_pickup_does_not_clobber_e1) \
    X(records_c_spawn_world_drop_count_zero_is_noop) \
    X(records_c_spawn_world_drop_low_type_caps_at_136) \
    X(records_c_spawn_world_drop_high_type_scans_all_200) \
    X(records_c_spawn_world_drop_commits_count_slots) \
    X(records_c_spawn_world_drop_age_in_0_to_7) \
    X(records_c_spawn_world_drop_vel_xz_paired_trig) \
    X(records_c_spawn_world_drop_low_type_skips_e1_write) \
    X(records_c_spawn_world_drop_high_type_writes_e1) \
    X(records_c_spawn_world_drop_explicit_override_writes_e2) \
    X(records_c_spawn_world_drop_ramp_fires_outside_window) \
    X(records_c_spawn_world_drop_ramp_suppressed_inside_window) \
    X(records_c_spawn_world_drop_owner_extra_aux_aux_recorded) \
    X(records_c_spawn_default_wrapper_forces_ramp) \
    X(records_c_spawn_typed_wrapper_passes_override) \
    X(records_c_spawn_default_wrapper_aux10_zero) \
    \
    X(records_b_spawn_trace_records_calls) \
    X(records_b_spawn_trace_unimplemented_still_traces) \
    X(records_b_spawn_trace_reset_clears) \
    X(records_b_spawn_entity_24_pure_preamble) \
    X(records_b_spawn_entity_writes_owner_ptr_to_owner_a_slot) \
    X(records_b_spawn_entity_alt_pos_path_when_flag_not_minus_one) \
    X(records_b_spawn_entity_copies_matrix) \
    X(records_b_spawn_entity_byte_pair_zeros_low_two_only) \
    X(records_b_spawn_entity_sequence_counter_increments) \
    X(records_b_spawn_entity_skips_alive_slots) \
    X(records_b_spawn_entity_table_full_no_commit) \
    X(records_b_spawn_entity_unimplemented_no_commit) \
    X(records_b_spawn_entity_60_writes_rot_x_from_owner_ea4) \
    X(records_b_spawn_entity_82_scale_2_and_rot_x) \
    X(records_b_spawn_npc_e_pure_preamble) \
    X(records_b_spawn_npc_copies_matrix_from_owner_39c) \
    X(records_b_spawn_npc_all_three_anchor_types_commit) \
    X(records_b_spawn_npc_shares_seq_counter_with_entity) \
    X(records_b_spawn_npc_unimplemented_no_commit) \
    X(records_b_spawn_drives_counter_scan) \
    X(records_b_spawn_entity_drift_writes_rot_x_from_npc_bend) \
    X(records_b_spawn_entity_drift_writes_vel_from_owner_ea4) \
    X(records_b_spawn_entity_drift_writes_pos_delta_from_preamble) \
    X(records_b_spawn_entity_drift_scale_x_per_type) \
    X(records_b_spawn_entity_drift_tail_writes_drag_aux_c8) \
    X(records_b_spawn_entity_drift_writes_random_rot_z) \
    X(records_b_spawn_entity_drift_all_six_types_implemented) \
    X(records_b_spawn_entity_cluster_a_4d_writes_vel_y_and_life) \
    X(records_b_spawn_entity_cluster_a_main6_overrides_pos) \
    X(records_b_spawn_entity_cluster_a_53_pos_y_no_lift_and_byte) \
    X(records_b_spawn_entity_cluster_a_default_types_pos_with_lift) \
    X(records_b_spawn_entity_cluster_a_51_writes_scale_x_1_5) \
    X(records_b_spawn_entity_cluster_a_4f_spawns_3_particles) \
    X(records_b_spawn_entity_cluster_a_50_spawns_5_particles) \
    X(records_b_spawn_entity_cluster_a_a5_spawns_6_particles) \
    X(records_b_spawn_entity_cluster_a_a6_spawns_8_particles) \
    X(records_b_spawn_entity_cluster_a_per_particle_angle_shifts) \
    X(records_b_spawn_entity_cluster_a_vel_uses_local_10_0_3_for_4d) \
    X(records_b_spawn_entity_cluster_a_vel_uses_local_10_0_5_for_4e) \
    X(records_b_spawn_entity_cluster_a_4e_rot_x_equals_local_c) \
    X(records_b_spawn_entity_cluster_a_implemented_macro) \
    X(records_b_spawn_entity_mega_77_one_particle) \
    X(records_b_spawn_entity_mega_73_four_particles) \
    X(records_b_spawn_entity_mega_7c_five_particles_with_neg_age) \
    X(records_b_spawn_entity_mega_76_eight_particles_part_idx_flag) \
    X(records_b_spawn_entity_mega_78_eight_with_life_mult) \
    X(records_b_spawn_entity_mega_7e_life_mult_and_scale) \
    X(records_b_spawn_entity_mega_pos_with_bend_mode_else) \
    X(records_b_spawn_entity_mega_pos_with_bend_mode_0) \
    X(records_b_spawn_entity_mega_pos_with_bend_mode_4) \
    X(records_b_spawn_entity_mega_7b_rot_x_is_local_c) \
    X(records_b_spawn_entity_mega_7a_local_c_override) \
    X(records_b_spawn_entity_mega_7c_rebound_pos_decremented) \
    X(records_b_spawn_entity_mega_implemented_macro) \
    X(records_b_spawn_npc_cluster_b_4d_writes_basic_fields) \
    X(records_b_spawn_npc_cluster_b_4f_spawns_3_particles) \
    X(records_b_spawn_npc_cluster_b_a6_spawns_8_particles) \
    X(records_b_spawn_npc_cluster_b_per_particle_shifts) \
    X(records_b_spawn_npc_cluster_b_4e_one_particle) \
    X(records_b_spawn_npc_cluster_b_implemented_macro) \
    X(records_b_spawn_npc_56_matrix_init_and_lift) \
    X(records_b_spawn_npc_56_matrix_is_roty_times_rotx) \
    X(records_b_spawn_npc_53_low_lift) \
    X(records_b_spawn_npc_51_mid_lift_cap_1) \
    X(records_b_spawn_npc_68_player_aim_alt_target) \
    X(records_b_spawn_npc_lab_00447584_group_b_preamble_only) \
    X(records_b_spawn_npc_explicit_return_group) \
    X(records_b_spawn_entity_3e_uses_owner_ea4_rot_x) \
    X(records_b_spawn_entity_5f_uses_owner_ea4_rot_x) \
    X(records_b_spawn_entity_23_yaw_branch_writes_full_pose) \
    X(records_b_spawn_entity_23_people_branch_reads_target) \
    X(records_b_spawn_entity_23_writes_matrix_via_rotation_x) \
    X(records_b_spawn_entity_29_yaw_branch_pos_no_vel_writes) \
    X(records_b_spawn_entity_29_people_branch_no_ground_default) \
    X(records_b_spawn_entity_29_ground_hook_clamps_pos_y) \
    X(records_b_spawn_entity_30_yaw_branch) \
    X(records_b_spawn_entity_30_people_branch_normalizes_vel) \
    X(records_b_spawn_entity_30_people_branch_zero_distance_keeps_vel) \
    X(records_b_spawn_entity_9b_bend_and_life) \
    X(records_b_spawn_entity_9d_full_pose_and_explicit_return) \
    X(records_b_spawn_entity_c8j8_implemented_macro) \
    X(records_b_spawn_entity_58_drift_with_drag) \
    X(records_b_spawn_entity_100_anchor_cone) \
    X(records_b_spawn_entity_74_mode0_pos_x_shift) \
    X(records_b_spawn_entity_79_mode_else_pos_z_shift) \
    X(records_b_spawn_entity_65_spawns_8_particles) \
    X(records_b_spawn_entity_6a_rot_x_strides) \
    X(records_b_spawn_entity_61_single_with_aux_c8_zero) \
    X(records_b_spawn_entity_62_scale_0p45) \
    X(records_b_spawn_entity_8a_8b_scale_distinguished) \
    X(records_b_spawn_entity_lab_00444be6_scales) \
    X(records_b_spawn_entity_6d_to_70_spawns_3_with_part_idx_minus_1) \
    X(records_b_spawn_entity_71_72_75_7d_per_type_state) \
    X(records_b_spawn_entity_8_zero_vel_anchor) \
    X(records_b_spawn_entity_c8j9_implemented_macro) \
    X(records_b_spawn_entity_68_implemented) \
    X(records_b_spawn_entity_68_empty_people_uses_fallback) \
    X(records_b_spawn_entity_68_matching_people_uses_target) \
    X(records_b_spawn_entity_68_sister_gate_blocks_match) \
    X(records_b_spawn_entity_68_distance_gate_blocks) \
    X(records_b_spawn_entity_68_distance_is_horizontal_only) \
    X(records_b_spawn_entity_68_selector_picks_nth_match) \
    X(records_b_spawn_entity_68_selector_out_of_range_falls_back) \
    X(records_b_spawn_npc_33_alt_pos_and_vel_from_pos_y) \
    X(records_b_spawn_npc_27_lifts_pos_y_to_plus8) \
    X(records_b_spawn_npc_2b_amp_multiplier_on_owner_424) \
    X(records_b_spawn_npc_26_2a_lift_distinguished) \
    X(records_b_spawn_npc_31_32_amp_scaling) \
    X(records_b_spawn_npc_25_lifts_pos_y_to_plus_8p8) \
    X(records_b_spawn_npc_3b_simple_vel_no_pos_writes) \
    X(records_b_spawn_npc_28_atan2_and_pos_doubled_vel) \
    X(records_b_spawn_npc_38_pos_from_alt_source) \
    X(records_b_spawn_npc_21_invariant_pos_and_vel_y) \
    X(records_b_spawn_npc_6b_npc_bend_amp_jitter) \
    X(records_b_spawn_npc_6c_pos_from_vel_times_3) \
    X(records_b_spawn_npc_1f_amp_switch_on_owner_424) \
    X(records_b_spawn_npc_c8j12_implemented_macro) \
    X(records_b_spawn_npc_2f_six_particle_fan) \
    X(records_b_spawn_npc_2f_rot_z_spacing) \
    X(records_b_spawn_npc_36_cap_8_indexed_pos) \
    X(records_b_spawn_npc_2e_sign_flip_tail) \
    X(records_b_spawn_npc_3c_minimal_drag_zero) \
    X(records_b_spawn_npc_98_five_particle_per_index_shifts) \
    X(records_b_spawn_npc_5a_zero_vel_atan2_const) \
    X(records_b_spawn_npc_f_12_scale_only) \
    X(records_b_spawn_npc_9c_bend_and_life_mult) \
    X(records_b_spawn_npc_3a_player_pos_centered_jitter) \
    X(records_b_spawn_npc_34_eight_particle_player_target) \
    X(records_b_spawn_npc_34_alt_pos_player_offset) \
    X(records_b_spawn_npc_34_frame_counter_rotates_table) \
    X(records_b_spawn_npc_16_17_part_idx_minus_one) \
    X(records_b_spawn_npc_c8j13_implemented_macro) \
    X(records_b_spawn_npc_lab_42831_rot_x_only) \
    X(records_b_spawn_npc_c8j11_implemented_macro) \
    X(records_b_spawn_npc_mega_b_cap_per_type) \
    X(records_b_spawn_npc_mega_b_pos_and_alt_pos) \
    X(records_b_spawn_npc_mega_b_mode_dispatch) \
    X(records_b_spawn_npc_mega_b_a4_skips_aux_c8) \
    X(records_b_spawn_npc_mega_b_scale_x_per_type) \
    X(records_b_spawn_npc_mega_b_a3_part_idx_quirk) \
    X(records_b_spawn_npc_mega_b_a4_clamp_away_from_zero) \
    X(records_b_spawn_npc_84_pos_direct_no_bend_spread) \
    X(records_b_spawn_npc_96_bend_spread_pos) \
    X(records_b_spawn_npc_84_dist_clamp_min_5) \
    X(records_b_spawn_npc_mega_b_7c_rebound)

#define T_DECL(n) extern int test_##n(void);
TESTS(T_DECL)
#undef T_DECL

static struct test_case g_tests[] = {
#define T_ENTRY(n) { #n, test_##n },
    TESTS(T_ENTRY)
#undef T_ENTRY
};

int main(int argc, char *argv[])
{
    int total   = (int)(sizeof(g_tests) / sizeof(g_tests[0]));
    int passed  = 0, failed = 0, skipped = 0;
    const char *filter = (argc > 1) ? argv[1] : NULL;

    for (int i = 0; i < total; i++) {
        if (filter && !strstr(g_tests[i].name, filter)) continue;
        printf("run  %s\n", g_tests[i].name);
        int rc = g_tests[i].fn();
        if      (rc == 0) { printf("pass %s\n", g_tests[i].name); passed++;  }
        else if (rc == 2) { printf("skip %s\n", g_tests[i].name); skipped++; }
        else              { printf("FAIL %s\n", g_tests[i].name); failed++;  }
    }
    int run_count = passed + failed + skipped;
    printf("\n%d passed, %d failed, %d skipped (%d run, %d registered)\n",
           passed, failed, skipped, run_count, total);
    return failed ? 1 : 0;
}
