#!/usr/bin/env python3
"""Cchr.2b — turn a retail --chr-leaf capture into a --force-player-sprite
inject file (strategy-B step 5).

Reads a chr_leaf.jsonl (written by `frida_capture.py --chr-leaf`), picks the
leaf call that drew the player — the leaf_in whose char_id matches the
frame's player_char_id and whose world-matrix translation is closest to the
captured player_pos — and writes the flat inject file main.c's
--force-player-sprite parser consumes:

    char_id <int>
    color   <hex u32>
    tex     <w> <h>
    world   <16 floats, row-major>
    actor   <17 ints>
    sheet   <name|->

With --emit-expected it also prints the paired leaf_out vertex buffer (the
geometry retail built for that exact call), so you can eyeball it against the
port's chr_sprite_build_quads output for the same inputs.

Usage:
    chr_leaf_to_inject.py <run_dir>/chr_leaf.jsonl [-o inject.txt]
                          [--frame N] [--sheet PATH] [--emit-expected]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _dist2(a, b):
    return sum((x - y) ** 2 for x, y in zip(a, b))


def pick_player_leaf(records: list[dict], frame: int | None):
    """Return (record, leaf_in, leaf_out_or_None) for the player's leaf call."""
    best = None  # (score, rec, leaf_in, leaf_out)
    for rec in records:
        if frame is not None and rec.get("frame") != frame:
            continue
        pcid = rec.get("player_char_id", -1)
        ppos = rec.get("player_pos") or [0.0, 0.0, 0.0]
        events = rec.get("events") or []
        # Pair each leaf_in with the next leaf_out (the leaf draws once,
        # right after building).
        for i, ev in enumerate(events):
            if ev.get("ev") != "leaf_in":
                continue
            leaf_out = None
            for j in range(i + 1, len(events)):
                if events[j].get("ev") == "leaf_out":
                    leaf_out = events[j]
                    break
                if events[j].get("ev") == "leaf_in":
                    break
            # Score: prefer matching player char id, then translation
            # nearest the player position. (matrix[12..14] = m41/m42/m43.)
            m = ev.get("matrix") or [0.0] * 16
            trans = [m[12], m[13], m[14]]
            id_match = 0 if (pcid >= 0 and ev.get("char_id") == pcid) else 1
            score = (id_match, _dist2(trans, ppos))
            if best is None or score < best[0]:
                best = (score, rec, ev, leaf_out)
    if best is None:
        return None
    return best[1], best[2], best[3]


def write_inject(leaf_in: dict, sheet: str, out) -> None:
    m = leaf_in.get("matrix") or [0.0] * 16
    actor = leaf_in.get("actor") or [0] * 17
    actor = (actor + [0] * 17)[:17]
    out.write(f"# generated by chr_leaf_to_inject.py\n")
    out.write(f"char_id {leaf_in.get('char_id', 0)}\n")
    out.write(f"color {leaf_in.get('color', 0xffffffff) & 0xffffffff:08x}\n")
    out.write(f"tex {leaf_in.get('tex_w', 0)} {leaf_in.get('tex_h', 0)}\n")
    out.write("world " + " ".join(repr(float(x)) for x in m[:16]) + "\n")
    out.write("actor " + " ".join(str(int(x)) for x in actor) + "\n")
    out.write(f"sheet {sheet}\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("jsonl", type=Path, help="chr_leaf.jsonl from --chr-leaf")
    ap.add_argument("-o", "--out", type=Path, default=None,
                    help="inject file to write (default: stdout)")
    ap.add_argument("--frame", type=int, default=None,
                    help="restrict to this capture frame")
    ap.add_argument("--sheet", default="-",
                    help="sheet texture path for SetTexture ('-' = none, "
                         "diffuse-only)")
    ap.add_argument("--emit-expected", action="store_true",
                    help="also print the paired leaf_out vertex buffer to stderr")
    args = ap.parse_args(argv)

    if not args.jsonl.exists():
        ap.error(f"{args.jsonl} not found")
    records = [json.loads(ln) for ln in args.jsonl.read_text().splitlines() if ln.strip()]
    if not records:
        ap.error(f"{args.jsonl} is empty")

    picked = pick_player_leaf(records, args.frame)
    if picked is None:
        print("no player leaf_in found in capture", file=sys.stderr)
        return 1
    rec, leaf_in, leaf_out = picked

    print(f"picked frame {rec.get('frame')} char_id={leaf_in.get('char_id')} "
          f"anim={ (leaf_in.get('actor') or [0])[0] } "
          f"cell={leaf_in.get('cell')} ncells={leaf_in.get('fd_ncells')} "
          f"(player_char_id={rec.get('player_char_id')})", file=sys.stderr)

    if args.out:
        with args.out.open("w") as f:
            write_inject(leaf_in, args.sheet, f)
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        write_inject(leaf_in, args.sheet, sys.stdout)

    if args.emit_expected and leaf_out is not None:
        verts = leaf_out.get("verts") or []
        print(f"--- expected leaf_out: prim_count={leaf_out.get('prim_count')} "
              f"stride={leaf_out.get('vb_stride')} verts={len(verts)} ---",
              file=sys.stderr)
        for k, v in enumerate(verts):
            print(f"  v{k}: pos=({v[0]:.4f},{v[1]:.4f},{v[2]:.4f}) "
                  f"diffuse=0x{v[3] & 0xffffffff:08x} uv=({v[4]:.5f},{v[5]:.5f})",
                  file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
