#!/usr/bin/env python3
"""Generate a derived PORT-DEBT registry for OpenRecet.

The port-LEDGER (tools/gen_port_ledger.py) tracks one kind of debt — engine
functions not yet referenced from src/.  This tool tracks the OTHER kind, the
one nothing else sees: **MVP shortcuts, synthetic-data tables, simplified state
machines, and `--force-*` injections living INSIDE code the ledger already
calls "ported".**  Those silently cap structural parity, so the un-MVP plan
(docs/plans/un-mvp-structural-parity.md, Step 1) makes them grep-able with one
canonical marker and a generated registry that can never go stale.

Tag convention (in a C comment, anywhere in src/):

    PORT-DEBT(<kind>, <engine-fn-or-NONE>): <one-line what's synthetic + retire cond>

  <kind> ∈ stub | synthetic-data | simplified | hardcode | scaffold | force-flag
  <engine-fn> names the real engine function that retires it (FUN_00xxxxxx),
              or NONE for pure scaffolding, or a §finding ref.

Example:

    /* PORT-DEBT(simplified, FUN_0048670f): raw atan2(dpad) impulse; real
       controller is the cc08 state machine w/ db05c facing. Retire = §69. */

Outputs (under docs/, git-tracked — they contain no vendor bytes):
  docs/port-debt.json   machine-readable: every tag, grouped counts
  docs/port-debt.md     human table grouped by kind + retiring engine-fn

Run from the repo root:  python3 tools/gen_port_debt.py
Add --check to exit 3 if the on-disk registry is stale (for the pre-commit hook).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"

DEBT_JSON = REPO / "docs" / "port-debt.json"
DEBT_MD = REPO / "docs" / "port-debt.md"

KINDS = ("stub", "synthetic-data", "simplified", "hardcode", "scaffold", "force-flag")

# PORT-DEBT(<kind>, <fn>): <desc up to end of line>
# Tolerant of whitespace; the description runs to the line end (one-line rule),
# with a trailing C comment terminator (*/) and surrounding "* " stars trimmed.
DEBT_RE = re.compile(
    r"PORT-DEBT\(\s*([a-z-]+)\s*,\s*([^)]*?)\s*\)\s*:\s*(.*)"
)


def clean_desc(raw: str) -> str:
    s = raw.strip()
    # Strip a trailing block-comment close and any continuation stars/space.
    s = re.sub(r"\*/\s*$", "", s).strip()
    s = re.sub(r"\s*\*\s*$", "", s).strip()
    return s


def scan_src() -> list[dict]:
    tags: list[dict] = []
    for path in sorted(SRC.rglob("*.c")) + sorted(SRC.rglob("*.h")):
        rel = str(path.relative_to(REPO))
        for lineno, line in enumerate(path.read_text(errors="replace").splitlines(), 1):
            m = DEBT_RE.search(line)
            if not m:
                continue
            kind = m.group(1)
            fn = m.group(2).strip() or "NONE"
            tags.append({
                "kind": kind,
                "engine_fn": fn,
                "desc": clean_desc(m.group(3)),
                "file": rel,
                "line": lineno,
                "kind_known": kind in KINDS,
            })
    tags.sort(key=lambda t: (t["kind"], t["engine_fn"], t["file"], t["line"]))
    return tags


def summarize(tags: list[dict]) -> dict:
    by_kind = {k: 0 for k in KINDS}
    unknown_kinds: dict[str, int] = {}
    by_fn: dict[str, int] = {}
    for t in tags:
        if t["kind_known"]:
            by_kind[t["kind"]] += 1
        else:
            unknown_kinds[t["kind"]] = unknown_kinds.get(t["kind"], 0) + 1
        if t["engine_fn"] != "NONE":
            by_fn[t["engine_fn"]] = by_fn.get(t["engine_fn"], 0) + 1
    return {
        "total": len(tags),
        "by_kind": by_kind,
        "unknown_kinds": dict(sorted(unknown_kinds.items())),
        "retiring_engine_fns": len(by_fn),
        "by_engine_fn": dict(sorted(by_fn.items(), key=lambda kv: (-kv[1], kv[0]))),
    }


def render_json(tags: list[dict], counts: dict) -> str:
    payload = {
        "_generated_by": "tools/gen_port_debt.py",
        "_note": "DERIVED FILE — do not edit by hand; run the generator. Tracks "
                 "MVP/synthetic shortcuts INSIDE ported code (PORT-DEBT tags), "
                 "the gap the port-ledger can't see. Pure function of src/, so "
                 "idempotent (safe for pre-commit --check).",
        "counts": counts,
        "tags": tags,
    }
    return json.dumps(payload, indent=1) + "\n"


def render_md(tags: list[dict], counts: dict) -> str:
    c = counts
    lines = [
        "# OpenRecet — PORT-DEBT registry",
        "",
        "> **DERIVED FILE** — regenerate with `python3 tools/gen_port_debt.py`",
        "> (also auto-regenerated by the pre-commit hook).",
        "",
        "MVP shortcuts, synthetic-data tables, simplified state machines, and",
        "`--force-*` injections living INSIDE code the port-ledger already calls",
        '"ported". These silently cap structural parity; the un-MVP plan',
        "(`plans/un-mvp-structural-parity.md`) retires them node-by-node. This is",
        "the answer to *\"what's still faked in code that looks done?\"*",
        "",
        "## Summary",
        "",
        f"- total open debts: **{c['total']}**",
        f"- distinct retiring engine functions: **{c['retiring_engine_fns']}**",
        "",
        "| kind | count | meaning |",
        "|------|------:|---------|",
        f"| stub | {c['by_kind']['stub']} | wired call boundary, body incomplete |",
        f"| synthetic-data | {c['by_kind']['synthetic-data']} | hand-made table standing in for real engine data |",
        f"| simplified | {c['by_kind']['simplified']} | reduced control flow / state machine vs retail |",
        f"| hardcode | {c['by_kind']['hardcode']} | fixed constant where the engine computes/sources it |",
        f"| scaffold | {c['by_kind']['scaffold']} | sanity-test plumbing, no engine counterpart (NONE) |",
        f"| force-flag | {c['by_kind']['force-flag']} | `--force-*` injection standing in for real sourcing |",
        "",
    ]
    if c["unknown_kinds"]:
        bad = ", ".join(f"{k} ({n})" for k, n in c["unknown_kinds"].items())
        lines += [
            f"> ⚠️  **{sum(c['unknown_kinds'].values())} tag(s) use an unknown kind**: {bad}.",
            f"> Valid kinds: {', '.join(KINDS)}.",
            "",
        ]

    # Grouped by retiring engine function (the migration unit — porting one fn
    # may retire several tags at once).
    lines += ["## By retiring engine function", ""]
    if c["by_engine_fn"]:
        lines += ["| engine fn | open debts |", "|-----------|-----------:|"]
        for fn, n in c["by_engine_fn"].items():
            lines.append(f"| {fn} | {n} |")
        lines.append("")

    # Full table grouped by kind.
    for kind in KINDS:
        rows = [t for t in tags if t["kind"] == kind]
        lines.append(f"## {kind} ({len(rows)})")
        lines.append("")
        if not rows:
            lines += ["_none_", ""]
            continue
        lines += ["| retire | location | what's synthetic |",
                  "|--------|----------|------------------|"]
        for t in rows:
            loc = f"{t['file']}:{t['line']}"
            desc = t["desc"].replace("|", "\\|")
            lines.append(f"| {t['engine_fn']} | {loc} | {desc} |")
        lines.append("")

    # Any tags with an unknown kind won't show above — list them so they're
    # never silently dropped.
    unknown = [t for t in tags if not t["kind_known"]]
    if unknown:
        lines += ["## unknown-kind (fix these tags)", "",
                  "| kind | retire | location | what's synthetic |",
                  "|------|--------|----------|------------------|"]
        for t in unknown:
            loc = f"{t['file']}:{t['line']}"
            desc = t["desc"].replace("|", "\\|")
            lines.append(f"| {t['kind']} | {t['engine_fn']} | {loc} | {desc} |")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 3 if on-disk registry differs from a fresh gen")
    args = ap.parse_args()

    tags = scan_src()
    counts = summarize(tags)
    out = {
        DEBT_JSON: render_json(tags, counts),
        DEBT_MD: render_md(tags, counts),
    }

    if args.check:
        stale = [p.name for p, txt in out.items()
                 if not p.exists() or p.read_text() != txt]
        if stale:
            print(f"port-debt registry stale: {', '.join(stale)} "
                  f"(run: python3 tools/gen_port_debt.py)", file=sys.stderr)
            return 3
        print("port-debt registry up to date")
        return 0

    for path, txt in out.items():
        path.write_text(txt)
    print(f"wrote {DEBT_JSON.name}, {DEBT_MD.name}")
    bk = counts["by_kind"]
    print(f"  {counts['total']} open debts across {counts['retiring_engine_fns']} "
          f"engine fns; " + ", ".join(f"{k} {bk[k]}" for k in KINDS))
    if counts["unknown_kinds"]:
        print(f"  WARNING: unknown kinds: {counts['unknown_kinds']}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
